### ISSUE TITLE
Please add .pc or/and .cmake files to find spglib

### ISSUE THREAD

**Issue by yurivict** [spglib/spglib#102]
cmake installs the header into include/ while before it was installed into include/spglib/, and depending projects have to guess its location and fail (fox example, avogadrolibs).

**Comment by atztogo** [comment]
How can we do?
What is the mechanism of guessing the location of header files in general?
Which is easier to change in spglib or avogadrolibs?

**Comment by yurivict** [comment]
Here is an example of a .pc file: https://docs.conan.io/en/1.8/integrations/pkg_config_pc_files.html
pkg-config uses them to find packages.

> What is the mechanism of guessing the location of header files in general?
In case of avogadrolibs it's just a fixed path. They can't do much when no .pc and no cmake files to search the package are installed.

**Comment by atztogo** [comment]
Thanks for explanation. I don't know how many but non-negligible number of codes may depend on spglib. So if only adding .pc can solve this issue, it would be nice to add it.

Now I have completely no idea how I should do. Can you make .pc for spglib and send a pull request?

**Comment by atztogo** [comment]
Can I close this issue?

**Comment by yurivict** [comment]
I am not a dev of spglib. I reported the problem, thousands of projects have .pc files. If you thing that it isn't important for you then close it. It's totally up to you.

**Comment by atztogo** [comment]
I don't know how to write .pc well and at this moment, for me, it's not important, so I don't want to spend my time for it. Please send pull request if you want to put the file in the repository.
