### ISSUE TITLE
Error in get_symmetry with a given threshold in versions after 1.14.1

### ISSUE THREAD

**Issue by mesonepigreco** [spglib/spglib#104]
Dear developers,

I think I found a bug that is affecting the newest version of spglib (version 1.14 works), or at least the python interface.

When I ask the symmetry group of a structure by with a python script, by passing a threshold, it correctly identify the group.

However, when I ask the symmetry operations, it seems to ignore the threshold parameters.

I attach an example that works properly with spglib==1.14.1 but not with spglib==1.15.1.

The example requires ASE installed just to read the ".cif" file (then it converts the structure in the spglib cell). 
It is a slightly displaced C2/c group structure.

If I ask the symmetry group without specifying a threshold, it correctly says it is P1 (1), while if I use a small threshold (0.05) it recognizes the C2/c (4) group.

Then I ask the code the symmetries and the rotations, by specifying the same threshold that allows recognizing the C2/c group, but it returns just the identity matrix.

As I told you, if I use an older version of spglib, the code works properly.

Is it a bug? will it be solved in the next release?

Thanks for your attention,

Best regards,
[test.zip](https://github.com/spglib/spglib/files/4745796/test.zip)

**Comment by atztogo** [comment]
I don't use ASE. Could you write the script without using ASE? Instead, please use the tuple format written here.
https://spglib.github.io/spglib/python-spglib.html#crystal-structure-cell.

**Comment by mesonepigreco** [comment]
Sorry, 
Here the version without ASE
[test.zip](https://github.com/spglib/spglib/files/4747342/test.zip)

**Comment by atztogo** [comment]
I see. If you specify the keyword of the keyword argument `symprec`, it works. This issue happened because I updated the method `get_symmetry` to insert `is_magnetic=True` in this way,

https://github.com/spglib/spglib/blob/f665008abcd9283125657bbf4c1c53d64647c9b0/python/spglib/spglib.py#L51-L54

I always do my best to explicitly specify the keyword, because this problem can happen when API provider changes the order of keyword arguments. But for spglib, at least the documentation is not very correct, and I had to be more careful not to change it. I will fix it in the next release. Until then, please do specify the keyword.

Your script was helpful. I am happy if you could give me the script in the way like below. This is not only to you, but to people who kindly give report in python script. I prefer to communicate in the way all data are also visible on gihub issue, which is like below.

In addition, I asked you not to use ASE. Because we can have unexpected problem due to using ASE. Then our communication may not go smoothly.

```python
import spglib
import numpy as np

cell_dat = """2.835350000000000037e+00 0.000000000000000000e+00 0.000000000000000000e+00
-6.483934765775929004e-03 5.020295812857042961e+00 0.000000000000000000e+00
-1.415017079891668583e+00 -5.489537649562379641e-03 2.457011630231173527e+00"""

coords_dat = """4.805068736366261972e-01 1.100077730747439225e-01 5.958789987874099081e-01
1.159102427785764222e-01 3.914970213362040097e-01 5.975721124661629302e-01
5.172158999787154210e-01 8.916868806863754715e-01 4.029325656496189900e-01
8.817570158443425177e-01 6.113756186416052785e-01 4.055821257574755978e-01
5.018406182627797030e-01 1.229143270312045150e-01 8.626990626136109563e-01
3.629996829046666651e-01 3.791311903543652662e-01 8.635089895897452017e-01
4.979544951354510363e-01 8.799722997056133034e-01 1.350298858653691536e-01
6.381512083958887915e-01 6.231459899349993670e-01 1.379358550159214547e-01
7.832262060878121268e-01 1.411538705501011737e-01 3.541619377349576880e-01
5.682272188008401503e-01 3.615130660847658550e-01 3.538607588594102626e-01
2.137955362771505607e-01 8.607918286086735371e-01 6.465299596818402383e-01
4.270320535109443094e-01 6.403895574761809817e-01 6.420489064118709566e-01
9.730648113090406559e-01 1.257184167946990561e-01 8.093904016417146075e-01
8.364749383010358086e-01 3.762176024712994837e-01 8.075711184340158555e-01
2.909115516861946263e-02 8.778634471026612873e-01 1.938574462324320347e-01
1.591197380403312212e-01 6.268223375103959549e-01 1.882774970651950597e-01
2.579844393455132598e-02 1.314806429350207084e-01 3.263883614277184320e-01
2.981420340860022056e-01 3.741091061614886248e-01 3.276012168995174889e-01
9.696678349899839899e-01 8.732679806802634559e-01 6.727569417632955906e-01
6.987241520104789938e-01 6.304639701357470649e-01 6.749506635730262438e-01
2.404469224879757783e-01 1.274101582273174660e-01 5.404532822154616001e-02
8.125525978202700061e-01 3.764190669821315116e-01 5.192893612310470891e-02
7.596598065887396611e-01 8.749674900656122523e-01 9.481972334058408336e-01
1.886653242942928632e-01 6.267898823851706380e-01 9.472855568095891465e-01"""


def test_symmetries():
    lattice = np.fromstring(cell_dat, dtype=float, sep=' ').reshape(3, 3)
    positions = np.fromstring(coords_dat, dtype=float, sep=' ').reshape(-1, 3)
    struct = (lattice, positions, [1, ] * len(positions))

    tolerance = 0.05

    spgroup1 = spglib.get_spacegroup(struct, symprec=tolerance)
    spgroup2 = spglib.get_spacegroup(struct)
    print("Space group:", spgroup2)
    print("Space group with high tolerance:", spgroup1)

    symmetries = spglib.get_symmetry(struct, symprec=tolerance)
    n_sym = len(symmetries["rotations"])
    print("Number of symmetries: {}".format(n_sym))
    print("(The C2/c group has 4 symmetries)")

    assert n_sym == 4


if __name__ == "__main__":
    test_symmetries()
```

**Comment by mesonepigreco** [comment]
Thank you! Ok, next time I will provide a script in the way you suggested.
Bests,
Lorenzo

**Comment by atztogo** [comment]
I think it's OK to close this issue. Please reopen when you need.
