### ISSUE TITLE
symmetry operations order

### ISSUE THREAD

**Issue by aslarsen** [spglib/spglib#107]
Hi
When getting the rotations and translation matrices for space group serial number 212 (F d d 2) and using the python interface – the first symmetry operations is not the identity operation, but instead I get.
rotation
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
translation
 [0.  0.5 0.5]
 for other space groups the identity symmetry operation is the first one, I don’t think this is the intended behaviour for space group 212?

**Comment by atztogo** [comment]
Do you have an example script?

**Comment by aslarsen** [comment]
If you print the translation part of the symmetry operation for all space groups, then for space group 212, 213 and 214 the first symmetry operation is not the identity operation. I can make a workaround in my code for this, but it would be nice if the order would be consistent for all space groups.
```
import numpy as np
import spglib

for space_group in range(1,531):
    symmetry = spglib.get_symmetry_from_database(space_group)
    rotations, translations = np.ndarray.astype(symmetry["rotations"], float), np.ndarray.astype(symmetry["translations"], float)
    print (space_group, translations[0])
```

**Comment by atztogo** [comment]
Thanks. I looked for the reason.

The data are stored in `src/spg_database.c`. The data are created from Hall symbols (http://cci.lbl.gov/sginfo/hall_symbols.html). Very before, I wrote the code to decode the Hall symbols in https://github.com/spglib/spglib/blob/develop/database/hall2operations.py.

The order of the symmetry operations for each Hall symbol is determined by the algorithm that I implemented. It seems there is no guarantee that identity operation must come first. The decoded symmetry operations form the expected group if translation group is multiplied. So I think theoretically no problem. 

It would be nice that the identity operation comes first. For this, `hall2operations.py` has to be changed. I'm not sure if I can work for this soon or not.

**Comment by atztogo** [comment]
I fixed this issue at the commit, https://github.com/spglib/spglib/commit/a7a2ccedcdb382c6634d276a27a04e6b69c7cc74. Probably OK.

**Comment by aslarsen** [comment]
awesome

**Comment by atztogo** [comment]
Can I close this issue?

**Comment by aslarsen** [comment]
Yes.
