### ISSUE TITLE
Recalculating correct multiplicities for the Wyckoff positions from get_symmetry_dataset(..) output

### ISSUE THREAD

**Issue by CompRhys** [spglib/spglib#108]
In the output dictionary when using `spglib.get_symmetry_dataset(..)` from the python package, we have "wyckoffs", "equivalent_sites" and "crystallographic_orbits". From these I have been attempting to recalculate the known multiplicities of the Wyckoff positions but have not been able to find a robust approach. Is this possible from the current outputs?

**Comment by atztogo** [comment]
From those three, I don't think it is possible.
