### ISSUE TITLE
Can not install python package on Windows 10

### ISSUE THREAD

**Issue by angushphys** [spglib/spglib#109]
Python 3.8.5
pip 20.2.2
Widows 10

When using `pip install spglib`, an error message is presented.
The error message is follow.
Noting there are some _mojibake_ after the line
 `d:\programs\python_3_8\include\pyconfig.h(59): fatal error C1083:`

     Collecting spglib
       Using cached spglib-1.16.0.tar.gz (723 kB)
       Installing build dependencies ... done
       Getting requirements to build wheel ... done
         Preparing wheel metadata ... done
     Requirement already satisfied: numpy in d:\programs\python_3_8\lib\site-packages (from spglib) (1.19.1)
     Building wheels for collected packages: spglib
       Building wheel for spglib (PEP 517) ... |  WARNING: Subprocess output does not appear to be encoded as cp932
     error
       ERROR: Command errored out with exit status 1:
        command: 'd:\programs\python_3_8\python.exe' 'd:\programs\python_3_8\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\UserOne\AppData\Local\Temp\tmpo4t0p841'
            cwd: C:\Users\UserOne\AppData\Local\Temp\pip-install-wxzh9wmp\spglib
       Complete output (18 lines):
       setuptools is used.
       running bdist_wheel
       creating build
       creating build\lib.win-amd64-3.8
       creating build\lib.win-amd64-3.8\spglib
       copying spglib\spglib.py -> build\lib.win-amd64-3.8\spglib
       copying spglib\__init__.py -> build\lib.win-amd64-3.8\spglib
       running build_ext
       building 'spglib._spglib' extension
       creating build\temp.win-amd64-3.8
       creating build\temp.win-amd64-3.8\Release
       creating build\temp.win-amd64-3.8\Release\src
       cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc -Id:\programs\python_3_8\include -Id:\programs\python_3_8\include -IC:\Users\UserOne\AppData\Local\Temp\pip-build-env-nxef9cq9\overlay\Lib\site-packages\numpy\core\include /Tc_spglib.c /Fobuild\temp.win-amd64-3.8\Release\_spglib.obj
       _spglib.c
       d:\programs\python_3_8\include\pyconfig.h(59): fatal error C1083: 辟｡豕暮幕蝠溷桁蜷ｫ讙疲｡\x88: 'io.h': No such file or directory
       error: command 'D:\\Programs\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.27.29110\\bin\\Hostx64\\x64\\cl.exe' failed with exit code 2
       ----------------------------------------
       ERROR: Failed building wheel for spglib
     Failed to build spglib
     ERROR: Could not build wheels for spglib which use PEP 517 and cannot be installed directly

**Comment by atztogo** [comment]
This is probably not the issue of spglib itself. But it seems you don't have (or can't find) 'io.h' somewhere you should have it.

**Comment by atztogo** [comment]
I will close issue because of the reason above.
