### ISSUE TITLE
Trouble with HCP lattices

### ISSUE THREAD

**Issue by antoine-levitt** [spglib/spglib#111]
Originally reported at https://github.com/JuliaMolSim/DFTK.jl/issues/307
Spglib doesn't like (fails normalization and returns non-unitary rotations) the following lattice:
```
    [2 0 0];
    [1 √3 0];
    [0 0 2]
```
The bug occurs no matter what atoms I use.

**Comment by atztogo** [comment]
Who wrote the Julia interface?

**Comment by antoine-levitt** [comment]
We directly call the C interface, see https://github.com/JuliaMolSim/DFTK.jl/blob/master/src/external/spglib.jl (@mfherbst and @louisponet wrote it). The layer is pretty small so I'm pretty sure it's not to blame here.

**Comment by atztogo** [comment]
OK. Then could you provide an example in python? Please do not use ase.

**Comment by atztogo** [comment]
Or in C.

**Comment by antoine-levitt** [comment]
Seems the problem is on our side, sorry for the noise!

**Comment by atztogo** [comment]
OK!
