### ISSUE TITLE
Confirm the equivalence of different surfaces belong to different spacegroups which are related via the change-of-basis transformation.

### ISSUE THREAD

**Issue by hongyi-zhao** [spglib/spglib#112]
Dear Dr.  Atsushi,

Based on the descriptions in [this paper](https://pubs.acs.org/doi/pdf/10.1021/acs.chemmater.9b05047), see top left column on pp.3 for more info, I learned the following fact: 

`The (010) surface in C2/c is equivalent to the (001) surface in I2/b. And these two space groups are related through a change-of-basis transformation. An I2/b cell is with tetragonal lattice while a C2/c cell is related to the conventional monoclinic cell.`

But The above description is very abstract and difficult to understand, so I want to know whether I can have a better understanding of the problem based on the help of spglib?

Regards,
HY

**Comment by atztogo** [comment]
Spglib will not of help. You need to learn crystallography.
