### ISSUE TITLE
spglib and BoltzTraP2 on Windows 10

### ISSUE THREAD

**Issue by goodwilling** [spglib/spglib#113]
spglib works great with BoltzTraP2, pymatgen,  matminer and other python packages.

However, when I install BoltzTraP2 on Windows 10 (miniconda3 environment) using

pip  install  BoltzTraP2

the error always comes out as
-----------------
    running build_ext
    running build_spglib
    About to create a new build directory for spglib
    About to run 'cmake' for spglib
    -- Building for: Visual Studio 14 2015
    -- Selecting Windows SDK version  to target Windows 10.0.19041.
    -- The C compiler identification is MSVC 19.0.24215.1
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Build type: Release
    -- Configuring done
    -- Generating done
    -- Build files have been written to: C:/Users/test/AppData/Local/Temp/pip-install-q2qison6/BoltzTraP2/external/spglib-1.9.9/build-25elaq1f
    About to run 'make' for spglib
    make: *** No targets specified and no makefile found.  Stop.
-----------------

I have tried to compile spglib-1.9.9 in BoltzTraP2 using cygwin64 and get libsymspg.a successfully. 
However, when I run the setup.py of BoltzTraP2, the error comes out in the linking process: 
----------------------
   Creating library build\temp.win-amd64-3.7\Release\BoltzTraP2/sphere\frontend.cp37-win_amd64.lib and object build\temp.win-amd64-3.7\Release\BoltzTraP2/sphere\frontend.cp37-win_amd64.exp
libsymspg.a(spglib.o) : error LNK2001: unresolved external symbol __getreent
libsymspg.a(spglib.o) : error LNK2001: unresolved external symbol fprintf
libsymspg.a(symmetry.o) : error LNK2001: unresolved external symbol ___chkstk_ms
libsymspg.a(pointgroup.o) : error LNK2001: unresolved external symbol ___chkstk_ms
build\lib.win-amd64-3.7\BoltzTraP2\sphere\frontend.cp37-win_amd64.pyd : fatal error LNK1120: 3 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120
-----------------------

I wonder what is the problem in compling spglib-1.9.9 on Windows 10. 

Thank you very much.

**Comment by atztogo** [comment]
Your spglib is super old.
I have no idea about compilation on windows. If you use conda, why not using conda-forge package?

**Comment by goodwilling** [comment]
Thank you for your comment.  On Windows 10, I can use 

pip install  spglib

to install spglib as a python library and it works great inside pymatgen.

However, BoltzTraP2 seems not to use spglib as a python library, as it contains 
some C++ source codes in which spglib is called to get all information about 
symmetries.

**Comment by atztogo** [comment]
Then it is the issue of BoltzTraP2.

**Comment by atztogo** [comment]
I close this issue because long time no communication.
