### ISSUE TITLE
Outdated information for compilation on Windows

### ISSUE THREAD

**Issue by cubanpit** [spglib/spglib#118]
I found [this instructions](https://spglib.github.io/spglib/install.html) about building spglib, but they do not work on Windows because no Makefile is generated by CMake.
I was able to build and install everything by using
```
% cmake -DCMAKE_INSTALL_PREFIX="" ..
% cmake --build . --config Release
% cmake --install . --config Release
```
According to [this post](https://stackoverflow.com/a/48428846/15189262) the install target can be called this way only with CMake >= 3.15.
The following should work in any case
```
% cmake -DCMAKE_INSTALL_PREFIX="" ..
% cmake --build . --target install --config Release
```
I am not sure if this is the suggested way to build and install spglib on Windows but it seems to work. The documentation could be updated with this information.

**Comment by atztogo** [comment]
I don't use windows and have no idea about it. On windows, what kind of environment (WSL etc) do you use to compile spglib?

**Comment by atztogo** [comment]
You mean, on windows, no Makefile is generated, so you can't use make command. I didn't know that. Thanks. But to write documentation, I should know more in detail.

**Comment by cubanpit** [comment]
Yes, I confirm that no Makefile is generated, so the `make` command does not apply.
I use a Cygwin environment with Microsoft native tools (Visual Studio, MSbuild, etc.) and CMake 3.15.2.
My environment is probably equivalent to a native Microsoft environment (i.e. without Cygwin).
Let me know what kind of additional information you might need.

**Comment by cubanpit** [comment]
Update on the installation on Windows, this method does not actually work, for some reason CMake prints something that it is not actually doing.
As example, it prints the following
```
cd /user/path/spglib-1.16.0-c/_build && cmake --install . --config Release
-- Installing: /build/path/lib/symspg.lib
-- Installing: /build/path/bin/symspg.dll
-- Up-to-date: /build/path/lib/symspg.lib
-- Installing: /build/path/include/spglib.h
```
But those files are not actually in there.
I am no sure if this is a problem on spglib's side, maybe some CMake configuration missing?

**Comment by atztogo** [comment]
Thanks for your information. I will keep this issue open until and put a link from spglib documentation to this issue.

**Comment by cubanpit** [comment]
I managed to solve the issue using Windows paths instead of Unix paths, my bad.
CMake on Windows wants DOS path format for the install prefix, but having a mixed building environment I had environment variables in Unix format.
The following worked without issues:
```
% cmake -DCMAKE_INSTALL_PREFIX="$(shell cygpath -w "${BUILD_DIR}")" ..
% cmake --build . --config Release
% cmake --install . --config Release
```
I can confirm this approach works on Windows, let me know if you need additional information to include this in the documentation.

**Comment by atztogo** [comment]
Thanks again. I updated the documentation, https://spglib.github.io/spglib/install.html. I will update this when more information will be required by users.

**Comment by cubanpit** [comment]
Thank you for the update to the documentation.
I also managed to test the same approach on Linux (apart from the conversion of the path with `cygpath`, of course) and it works flawlessly.
So using `cmake` seems to work on these two platforms in the same way. Users should just remember about using their OS native path format.

**Comment by atztogo** [comment]
Thanks. Now I tried `cmake --build` and `cmake --install` on my macOS and conda and it works. This is the way that should be.
