### ISSUE TITLE
C-API spgat_standardize_cell with collinear spin?

### ISSUE THREAD

**Issue by romankempt** [spglib/spglib#121]
Hi,

I was just wondering if there is such a thing as standardization of the crystal structure considering collinear spin. E.g., I'm looking for a function in the C-API similar to this:

```
  int spgat_standardize_cell(double lattice[3][3],
                             double position[][3],
                             int types[],
                             int spins[],
                             const int num_atom,
                             const int to_primitive,
                             const int no_idealize,
                             const double symprec,
                             const double angle_tolerance);
```                             

Or should this simply be handled by assigning these atoms a different type? (I'm currently using the atomic number as the type)

**Comment by atztogo** [comment]
There is no standardization with collinear spin. This is because spglib doesn't have magnetic space group database in it.
