### ISSUE TITLE
pip installation seems to lack libsymspg.a

### ISSUE THREAD

**Issue by romankempt** [spglib/spglib#122]
It seems that installing spglib with `pip install spglib` does not provide the `libsymspg.a` anywhere in the `env/lib/` directory, where as `conda install spglib` does.

Is there any way to fix that?

**Comment by atztogo** [comment]
Honestly I have no idea how to do it, and probably have no time to work for it. It is more than welcome if somebody makes the PyPI package.

**Comment by LecrisUT** [comment]
Maybe a bit late, but pip installations should not be providing static libraries. These are only meant to be used for bundling a software. For that you should be using the cmake build and specifying the flags you need there.
