### ISSUE TITLE
Tolerance seems to have no effect when calling spg_get_dataset()

### ISSUE THREAD

**Issue by toxa81** [spglib/spglib#123]
Dear @atztogo !
In the example below I call `spg_get_dataset` twice with 1e-4 and 1e-14 tolerance. Both calls lead to the same list of lattice symmetries, which I believe is wrong. In particular, for the low tolerance the symmetry operation {{1,0,0},{0,-1,0},{0,0,-1}} is wrong as it leads to non-zero metric tensor with the non-zero elements greater than the tolerance. 
```
#include <spglib.h>
#include <stdio.h>

int main(int arg, char** argv)
{
    SpglibDataset* spg_dataset;

    double lattice[3][3] = {{4.47994, 6.14618e-08, 6.14618e-08},{0, 5.05112, -0.144273},{0, 0, 8.83069}};
    double pos[1][3] = {{0,0,0}};
    int types[1] = {0};

    printf("tolerance 1e-4\n");
    spg_dataset = spg_get_dataset(lattice, (double(*)[3])pos, types, 1, 1e-4);

    printf("num sym: %i\n", spg_dataset->n_operations);
    for (int isym = 0; isym < spg_dataset->n_operations; isym++) {
        printf("isym=%i\n", isym);
        for (int x = 0; x < 3; x++) {
            for (int y = 0; y < 3; y++) {
                printf("%i ", spg_dataset->rotations[isym][x][y]);
            }
            printf("\n");
        }
    }


    printf("tolerance 1e-14\n");
    spg_dataset = spg_get_dataset(lattice, (double(*)[3])pos, types, 1, 1e-14);

    printf("num sym: %i\n", spg_dataset->n_operations);
    for (int isym = 0; isym < spg_dataset->n_operations; isym++) {
        printf("isym=%i\n", isym);
        for (int x = 0; x < 3; x++) {
            for (int y = 0; y < 3; y++) {
                printf("%i ", spg_dataset->rotations[isym][x][y]);
            }
            printf("\n");
        }
    }
}
```
Output
```
tolerance 1e-4
num sym: 4
isym=0
1 0 0
0 1 0
0 0 1
isym=1
-1 0 0
0 -1 0
0 0 -1
isym=2
1 0 0
0 -1 0
0 0 -1
isym=3
-1 0 0
0 1 0
0 0 1
tolerance 1e-14
num sym: 4
isym=0
1 0 0
0 1 0
0 0 1
isym=1
-1 0 0
0 -1 0
0 0 -1
isym=2
1 0 0
0 -1 0
0 0 -1
isym=3
-1 0 0
0 1 0
0 0 1
```

Check of metric tensor in Mathematica

<img width="775" alt="image" src="https://user-images.githubusercontent.com/327435/117323277-09a07880-ae8f-11eb-8414-8abc86f5c352.png">

**Comment by atztogo** [comment]
Tolerance parameter in spglib is not mathematically well defined. It is a parameter like a reference. One reason is that only one parameter is not enough to define tolerance measures in many comparison inside spglib. I heuristically adjust the controls in symmetry findings and some parameters are even hard corded. To make spglib work as human being feeling happy is a nontrivial task.
If you have a good idea to improve this, please work on it! I believe there are plenty of things to be improved. For people who may be interested in it, I wrote https://arxiv.org/abs/1808.01590.

**Comment by toxa81** [comment]
Dear @atztogo !
Thanks for the link to the paper - a very instructive reading! And it explains exactly  the point where I struggle to understand the result
<img width="434" alt="image" src="https://user-images.githubusercontent.com/327435/117466510-15ee0980-af53-11eb-8d92-41c9fb78a61a.png">
For my example the left side (with sin^2(...)) is of the order of 10^-12. But the right side with epsilon^2 is 10^-28. So the criteria should not be fulfilled and the symmetry operation should be discarded. This is not happening and this is basically a reason for opening an issue here.

**Comment by toxa81** [comment]
Can it be because of the hardcoded 10^-12 constant?
<img width="525" alt="image" src="https://user-images.githubusercontent.com/327435/117470025-a2e69200-af56-11eb-812a-a6df570a789f.png">
so the cure is to increase the lattice distortion a little big?

**Comment by atztogo** [comment]
@tox81, I am back to this issue. The value `1e-12` is necessary to avoid always true the following
``` 
if (sin_dtheta2 * length_ave2 > symprec * symprec)
```
For example, this happens for your symprec that is too small so that the square is less than machine precision. For the precise control of the angle (i.e., non diagonal elements of metric tensor comparison), `angle_tolerance` exists.

These kinds of tolerance parameters have been adjusted following trial-and-error after years to work for majority of cases. So I am afraid of making change it.

**Comment by toxa81** [comment]
Hi @atztogo !
The machine precision is a good argument. What about taking square root of left- and right- hand sides:
```
if (abs(sin_dtheta) * length_ave > symprec)
```

**Comment by atztogo** [comment]
First I want you to understand that the aim of the code here is comparison of angle, but not metric tensor elements. This is not very easy to be done from symprec.

Your suggestion breaks the physical unit, so it should be like
```
if (sin_dtheta2 / 2 * sqrt(length_ave) > symprec)
```

But, this part is very weak again numerical noise.

https://github.com/spglib/spglib/blob/9df1894644bfe1a2f8cbdcf14f3ad31159d5fbd2/src/symmetry.c#L1046-L1057

For example, `sqrt(1 - cos1 * cos1)` enhances small value, if we get `(1 - cos1 * cos1)` is around 1e-16, the sqrt becomes 1e-8. In my feeling, it is difficult for me to have one best numerically stable comparison working for many different cases. In addition, spglib is already used for many codes as a library, if we change here, the behaviour can change. Some people might not be happy for it. So if you are very keen about this implementation, and you have a good idea to handle it, we may take the risk to change this part.

**Comment by toxa81** [comment]
Dear @atztogo ! I got the point and I agree with you.
