### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [spglib/spglib#128]
Problem
---------
On aarch64, ‘pip install spglib’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes more time to build the wheels than downloading and extracting the wheels from PyPi.

Resolution
-----------
On aarch64, ‘pip install spglib’ should download the wheels from PyPi.

@atztogo, Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by atztogo** [comment]
Thanks. It is nice to have it. But now travis-CI is not used. I consider moving the pypi package build to github workflow. This is because at some point (probably when spglib repository was moved from my account to spglib github organization), travis-CI started not working as I expcted.

**Comment by atztogo** [comment]
This is done.
