### ISSUE TITLE
Bug in Fortran interface - compile failure with NVIDIA/PGI compiler

### ISSUE THREAD

**Issue by krefson** [spglib/spglib#141]
There is a small bug in the Fortran interface file `spglib_f08.f90`. This file fails to compile with the NVIDIA/PGI compiler version 21-2.

`nvfortran -c spglib_f08.f90 
NVFORTRAN-S-0155-Derived type has not been declared - spglibdataset (spglib_f08.f90: 29)
  0 inform,   0 warnings,   1 severes, 0 fatal for spg_get_dataset
`
 The issue is that the variable SPGLIB_SUCCESS is used within an INTERFACE block, but not IMPORTed so it is not in scope. It seems that the GNU and Intel compilers  allow access to variables in the parent scope but this is NOT fortran 2003 and is an extension. 

Here's a patch

[spglib_f08.diff.gz](https://github.com/spglib/spglib/files/7570661/spglib_f08.diff.gz)
.

**Comment by atztogo** [comment]
Thanks @krefson. Your patch was merged to the develop branch.

**Comment by atztogo** [comment]
I close this issue because the fix is merged to the develop.
