### ISSUE TITLE
Uninitialized variable is_found

### ISSUE THREAD

**Issue by correaa** [spglib/spglib#145]
In our project, we are compiling spglib with some warning and we get that there maybe initialized variables.

```
cd /home/correaa/prj/inq/.build.nvcc/external_libs/spglib && /usr/bin/cc -DUSING_Libxc -I/home/correaa/prj/inq/.build.nvcc/_deps/catch2-src/src -I/home/correaa/prj/inq/PkgConfig::FFTW -I/home/correaa/prj/inq/external_libs/libxc/src -I/home/correaa/prj/inq/.build.nvcc/external_libs/libxc -I/home/correaa/prj/inq/.build.nvcc/external_libs/libxc/gen_funcidx -I/home/correaa/prj/inq/external_libs/spglib/src -isystem /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem /usr/lib/x86_64-linux-gnu/openmpi/include -Wall -O2 -fPIC -o CMakeFiles/symspg_static.dir/src/symmetry.o -c /home/correaa/prj/inq/external_libs/spglib/src/symmetry.c
/home/correaa/prj/inq/external_libs/spglib/src/spin.c: In function ‘spn_get_operations_with_site_tensors’:
/home/correaa/prj/inq/external_libs/spglib/src/spin.c:207:8: warning: ‘is_found’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  207 |     if (is_found) {
      |        ^
/home/correaa/prj/inq/external_libs/spglib/src/spin.c:158:31: note: ‘is_found’ was declared here
  158 |   int i, j, k, sign, num_sym, is_found;
```

It is difficult to see if all paths initialize `is_found` but in any case it seems that initializing it with `0` (`false`) would be sensible, either at the point of declaration or before entering the loops below.

**Comment by atztogo** [comment]
Do you mean the following line?

https://github.com/spglib/spglib/blob/f0794693b556253e2027519459edae42a882c8c1/src/spin.c#L167

Otherwise, could you tell me which version of spglib you use?

**Comment by correaa** [comment]
yes, must be that same variable.

We are using 1.16.1 according to `version.h`. 
I didn't notice it is not the latest (1.16.3?).

**Comment by atztogo** [comment]
Releases are found here, https://github.com/spglib/spglib/tags. The latest is v1.16.3.
See https://github.com/spglib/spglib/blob/master/ChangeLog.

**Comment by correaa** [comment]
glad to know it is fixed in latest versions
