### ISSUE TITLE
Hall group missing

### ISSUE THREAD

**Issue by afonari** [spglib/spglib#149]
Hi All,

Stumbled upon 19 space group setting that is missing from spglib (https://github.com/spglib/spglib/blob/develop/src/spg_database.c#L155) and set website (https://web.archive.org/web/20210117064350/http://pmsl.planet.sci.kobe-u.ac.jp/~seto/?page_id=37&lang=en), see attached CIF: [PYRIDO.cif.gz](https://github.com/spglib/spglib/files/8188521/PYRIDO.cif.gz).

It has the second setting of 19 group, listed here, item b: http://img.chem.ucl.ac.uk/sgp/large/019a.htm

**Comment by atztogo** [comment]
I can't understand what you mean.

**Comment by lan496** [comment]
@afonari Hi. As far as I understand, Hall symbols explicitly specify the settings and origins of space groups considered in International Tables for Crystallography A (ITA) (c.f. Appendix 1.4.2.3 in International Tables for Crystallography B (2011)). In ITA, for orthorhombic space groups (including No. 19), permutations of axes are only considered (c.f. Section 2.1.3.6.4 in ITA (2010)). For No. 19, all proper permutations of axes give the same space group (c.f. Table 2.1.3.4 of ITA). Thus, item b (http://img.chem.ucl.ac.uk/sgp/large/019bz1.htm) is not tabulated in Hall symbols although item b is transformed to item a by an orientation-preserving transformation.

**Comment by afonari** [comment]
Thanks for the comments.

From @lan496 comment, I don't understand what is the conclusion. Should this space group be added to the spglib?

**Comment by atztogo** [comment]
My conclusion is not to include your second setting of the space group type No 19. The technical reason is written by @lan496. We follow the Bilbao crystallographic server. See https://www.cryst.ehu.es/cgi-bin/cryst/programs/nph-def-ita_settings

Using https://www.cryst.ehu.es/cryst/get_gen.html with the number and pushing the button ITA Settings, you can find the list of the choices. For No.18

[18-1](https://www.cryst.ehu.es/cgi-bin/cryst/programs//nph-getgen?gnum=018&what=gp)
[18-2](https://www.cryst.ehu.es/cgi-bin/cryst/programs//nph-trgen?gnum=018&what=gp&trmat=c,a,b&unconv=P%202%2021%2021&from=ita)
[18-3](https://www.cryst.ehu.es/cgi-bin/cryst/programs//nph-trgen?gnum=018&what=gp&trmat=b,c,a&unconv=P%2021%202%2021&from=ita)

For No. 19

[19](https://www.cryst.ehu.es/cgi-bin/cryst/programs//nph-getgen?gnum=019&what=gp)
