### ISSUE TITLE
Unconventional Hall symbols in `spg_database.c`

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#155]
I am not sure if this is a bug or not. But, I have noticed some Hall symbols in `spg_database.c` differ from the list of Hall symbols in International Tables for Crystallography Vol. B (ITB).

In `spglib`, the so-called "V entry" in Hall symbols is not consistent with ITB: For example, in Table A1.4.2.7 of ITB, No. 151 is represented as `P 31 2 (0 0 4)`. On the other hand, `spg_database.c` represents it as `P 31 2c (0 0 1)`.
https://github.com/spglib/spglib/blob/188e6a5aec5424ce5bbdeebc98502439a4ae3713/src/spg_database.c#L480

**Comment by atztogo** [comment]
Thanks for your information. I didn't know it. The data in spglib seems old. However, I expect the matrix representation will be equivalent as space group. We should update it at some point in the future.

I just found hall symbol extension for [magnetic group.](https://onlinelibrary.wiley.com/doi/abs/10.1107/S1600576720015897) Maybe it would be good to work on this, too. I will try to find time...

**Comment by lan496** [comment]
Edited: hall_number=255 is omitted because spg_database and ITB give the same Hall symbol.

I also think the differences between `spg_database.c:spacegroup_types` and Table A1.4.2.7 in ITB (2010).
So I'll close this issue.
Just in case someone is curious about the differences, here is a list of the differences I've found.
```csv
hall_number, spg_database, Table A1.4.2.7 ITB (2010)
40, A -2yac, A -2yab
43, C -2ybc, C -2yac
46, B -2bc, B -2ab
49, A -2ac, A -2ab
52, C -2xbc, C -2xac
55, B -2xbc, B -2xab
91, -A 2yac, -A 2yab
94, -C 2ybc, -C 2yac
97, -B 2bc, -B 2ab
100, -A 2ac, -A 2ab
103, -C 2xbc, -C 2xac
106, -B 2xbc, -B 2xab
191, A 2 -2c, A 2 -2b
192, B 2 -2c, B 2 -2a
193, B -2c 2, B -2a 2
194, C -2b 2, C -2a 2
195, C -2b -2b, C -2a -2a
196, A -2c -2c, A -2b -2b
203, A 2 -2ac, A 2 -2ab
204, B 2 -2bc, B 2 -2ab
205, B -2bc 2, B -2ab 2
206, C -2bc 2, C -2ac 2
207, C -2bc -2bc, C -2ac -2ac
208, A -2ac -2ac, A -2ab -2ab
304, -C 2bc 2, -C 2ac 2
305, -C 2bc 2bc, -C 2ac 2ac
306, -A 2ac 2ac, -A 2ab 2ab
307, -A 2 2ac, -A 2 2ab
308, -B 2 2bc, -B 2 2ab
309, -B 2bc 2, -B 2ab 2
316, -C 2b 2, -C 2a 2
317, -C 2b 2b, -C 2a 2a
318, -A 2c 2c, -A 2b 2b
319, -A 2 2c, -A 2 2b
320, -B 2 2c, -B 2 2a
321, -B 2c 2, -B 2a 2
322, C 2 2 -1bc, C 2 2 -1ac
323, -C 2b 2bc, -C 2a 2ac
324, C 2 2 -1bc, C 2 2 -1ac
325, -C 2b 2c, -C 2a 2c
326, A 2 2 -1ac, A 2 2 -1ab
327, -A 2a 2c, -A 2a 2b
328, A 2 2 -1ac, A 2 2 -1ab
329, -A 2ac 2c, -A 2ab 2b
330, B 2 2 -1bc, B 2 2 -1ab
331, -B 2bc 2b, -B 2ab 2b
332, B 2 2 -1bc, B 2 2 -1ab
333, -B 2b 2bc, -B 2b 2ab
440, P 31 2c (0 0 1), P 31 2 (0 0 4)
442, P 32 2c (0 0 -1), P 32 2 (0 0 2)
472, P 61 2 (0 0 -1), P 61 2 (0 0 5)
474, P 62 2c (0 0 1), P 62 2 (0 0 4)
475, P 64 2c (0 0 -1), P 64 2 (0 0 2)
515, F -4c 2 3, F -4a 2 3
524, -F 4c 2 3, -F 4a 2 3
527, F 4d 2 3 -1cd, F 4d 2 3 -1ad
528, -F 4cvw 2vw 3, -F 4ud 2vw 3
```

**Comment by atztogo** [comment]
Let's follow ITB. I will work on it.

**Comment by site-g** [comment]
@lan496

> `255, -P 2 2bc, -P 2 2ac`

This line seems not correct, the No. 255 hall symbol in ITB is also `-P 2 2bc`, while `-P 2 2ac` is No. 254.

My conjecture of the hall symbol differences is that spglib uses hall symbols in [Seto's Page](https://yseto.net/?page_id=29%3E), which might come from [SgInfo](http://cci.lbl.gov/sginfo/hall_symbols.html), who admits the differences with ITB

> There are subtle differences compared to International Tables for Crystallography Volume B (ITVB), 2001, pp. 112-119. The unusual lattice symbol S in Table 1 below was dropped in ITVB, and some Hall symbols in Table 6 below were replaced with equivalent alternatives.

So the differences will also affect the layer group hall symbols, 3 of them should be updated
```
layer group hall number, space-group hall number, spg_database, Table A1.4.2.7 ITB (2010)
62, 195, c -2b -2b, c -2a -2a
63, 194, c -2b 2, c -2a 2
81, 316, -c 2b 2, -c 2a 2
```

**Comment by lan496** [comment]
@site-g Thanks! I have fixed the list in my comment.
