### ISSUE TITLE
niggli_reduce gives different results with vector and matrix input

### ISSUE THREAD

**Issue by nosarthur** [spglib/spglib#159]
The following code prints `[ 0.          0.          2.         -0.70710678  0.70710678  0.
 -0.70710678 -0.70710678  0.        ]`
```
from spglib import niggli_reduce

x = 2**0.5
y = 1 / x
input = [2, 0, 0, 0, x, y, 0, 0, y]
got = niggli_reduce(input)
print(got)
```
The convention here is `ax, bx, cx, ay, by, cy, az, bz, cz` according to https://atztogo.github.io/niggli/

If I turn `input` into 3x3 matrix, `niggli_reduce` returns a different result
```
input2 = np.array(input)
input2.shape = 3,3
got2 = niggli_reduce(input2)
print(got2)
```
It prints
```
[[ 0.          0.         -0.70710678]
 [ 0.          1.41421356  0.        ]
 [ 2.          0.          0.        ]]
 ```
`input2.T` produces the original results.

**Comment by nosarthur** [comment]
Actually the function docstring says the input should be 

```
            [[a_x, a_y, a_z],
             [b_x, b_y, b_z],
             [c_x, c_y, c_z]]
```
which is the transpose of what https://atztogo.github.io/niggli/ says

https://github.com/spglib/spglib/blob/c74cdaa72f886edc1975bee55954c053b115c767/python/spglib/spglib.py#L913

**Comment by atztogo** [comment]
It is explained at http://spglib.github.io/spglib/python-spglib.html#variables.

**Comment by nosarthur** [comment]
Thanks. I guess it's just a convention difference between spglib and niggli. Closing the case

**Comment by atztogo** [comment]
Yes, it is entirely the convention. I prefer representing basis vectors by column vectors following crystallographic convention. But popular codes such as ASE often take them as row vectors.
