### ISSUE TITLE
the choice of hall number in spg_get_hall_number_from_symmetry

### ISSUE THREAD

**Issue by qzhu2017** [spglib/spglib#163]
I recently came across the function of [spg_get_hall_number_from_symmetry](https://spglib.github.io/spglib/api.html#id19)[¶](https://spglib.github.io/spglib/api.html#spg-get-hall-number-from-symmetry)

It is said that the smallest one (the first description of the space-group type in International Tables for Crystallography) is chosen when multiple Hall numbers exist. 

In this case, this function will be identical to get_space_group_number.

I am wondering if you can output the true hall number that has non-standard setting,
for instance, the following operations
```
x, y, z, 
-x, -y, -z,
-x+1/2, y+1/2, -z+1/2,
x+1/2, -y+1/2, z+1/2
```
should belong to P21/n space group (Hall number 82),

Using the spglib function, it returns the hall number of 81. Is it possible to let it return the true hall number 82?

**Comment by atztogo** [comment]
The numerical operations are matrix representations of the space group type, and the different settings corresponding to the same space group type are equivalent as the space group. The difference in the matrix representation comers from the choice of, e.g., origin, orientation, etc.
Spglib assumes user's choice is arbitrary (can be translated or rotated or non-standard linear combination of basis vectors, etc), therefore spglib can't choose by itself the setting, i.e., users have to provide it. If you know exact standardized matrix representation of your crystal, you can just look up the table, which is considered not the task of the spglib. The matrix representation can be obtained by [get_symmetry_from_database](https://spglib.github.io/spglib/python-spglib.html#get-symmetry-from-database)](https://spglib.github.io/spglib/python-spglib.html#get-symmetry-from-database).

**Comment by atztogo** [comment]
I will close this issue because no reply for a while. Please reopen if necessary.
