### ISSUE TITLE
About the basis vectors of the primitive cell for space group 227 given by `spglib` and `cryst` packages.

### ISSUE THREAD

**Issue by hongyi-zhao** [spglib/spglib#165]
As described [here](https://spglib.github.io/spglib/definition.html#id11), the transformation matrix $P_F$ will be used for face centred (F) lattice:

![image](https://user-images.githubusercontent.com/11155854/179158762-6e9e8ae1-917c-4752-a107-1326a9f1d617.png)

In addition, I also confirmed this behavior as follows:
```python
from pymatgen.io.cif import CifParser
#https://pymatgen.org/pymatgen.symmetry.analyzer.html#pymatgen.symmetry.analyzer.SpacegroupAnalyzer
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

#https://materialsproject.org/materials/mp-66/cif?type=conventional_standard&download=true
#https://python.hotexamples.com/examples/pymatgen.symmetry.analyzer/SpacegroupAnalyzer/find_primitive/python-spacegroupanalyzer-find_primitive-method-examples.html
parser = CifParser("./C_mp-66_conventional_standard.cif")
structure = parser.get_structures(False)[0]
s = SpacegroupAnalyzer(structure)
p = s.find_primitive()

print("Basis vectors of the conventional cell: \n{}\n".format(structure.lattice))
print("space_group_number:", s.get_space_group_number(),"\n")
print("Basis vectors of the primitive cell: \n{}".format(p.lattice))

3.57371 0.0 2.1882662562904438e-16
5.746963994375892e-16 3.57371 2.1882662562904438e-16
0.0 0.0 3.57371

space_group_number: 227 

Basis vectors of the primitive cell: 
-1.786855 -1.786855 0.0
-1.786855 0.0 -1.786855
0.0 -1.786855 -1.786855
``` 
But I also noticed the following result given by `TranslationBasis` command implemented in [`cryst`](https://github.com/gap-packages/cryst) package:

```gap
gap> GenSG227Left:=[[[0, 1, 0, 0], [1, 0, 0, 0], [-1, -1, -1, 0], [0, 0, 0, 1]],
> [[-1, -1, -1, 0], [0, 0, 1, 0], [0, 1, 0, 0], [0, 0, 0, 1]],
> [[-1, 0, 0, 1/4], [0, -1, 0, 1/4], [1, 1, 1, 1/4], [0, 0, 0, 1]],
> [[0, 0, 1, 0], [1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 0, 1]],
> [[-1, 0, 0, 1/4], [0, -1, 0, 1/4], [0, 0, -1, 1/4], [0, 0, 0, 1]]];;
gap> 
gap> SG227Left:=AffineCrystGroupOnLeft(GenSG227Left);;
gap> TranslationBasis(SG227Left);
[ [ 1, 0, 0 ], [ 0, 1, 0 ], [ 0, 0, 1 ] ]
gap> TranslationBasis(SpaceGroupOnLeftIT(3, 227));
[ [ 1/2, 0, 1/2 ], [ 0, 1/2, 1/2 ], [ 0, 0, 1 ] ]
```
As you can see, the basis vectors picked up are different. Therefore, I am confused by the different base choices used by [`spglib`](https://github.com/spglib/spglib) and [`cryst`](https://github.com/gap-packages/cryst) packages as shown above. Any hints for this setting will be appreciated.

See [here](https://github.com/gap-packages/hap/issues/72#issuecomment-1185193775) for the related discussion.

Regards,
Zhao

**Comment by atztogo** [comment]
I don't use pymatgen. I don't use cryst. So I have no idea.

**Comment by hongyi-zhao** [comment]
The [pymatgen's find_primitive](https://github.com/materialsproject/pymatgen/blob/v2022.7.8/pymatgen/symmetry/analyzer.py#L333-L363) function is only a wrapper of spglib's counterpart under the hood. I was going to use spglib for the example used here, but spglib doesn't interface with the module that reads CIF files.

**Comment by atztogo** [comment]
Then we cannot communicate. Can I close this issue?

**Comment by hongyi-zhao** [comment]
OK. You can make corresponding treatment according to your own wishes and understanding.
