### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by josehgarciaa** [spglib/spglib#166]
In the installation instruction here: https://spglib.github.io/spglib/install.html

procedure should be

% mkdir _build && **cd** _build
% cmake -DCMAKE_INSTALL_PREFIX="" ..
% make
% make DESTDIR=/some/where install

The cd is missing in current version

**Comment by atztogo** [comment]
Thanks @josehgarciaa. I fixed it on develop.

**Comment by atztogo** [comment]
I close this issue because the documentation was updated.
