### ISSUE TITLE
Identify the space group using the generators in the affine matrix format.

### ISSUE THREAD

**Issue by hongyi-zhao** [spglib/spglib#189]
The following are two generators of a space group represented in the affine matrix format: 
```gap
# gap> GeneratorsOfGroup(SGc2false);
[ 
[[ 0, -1, 0, 1/4 ], [ 0, 0, -1, 1/4 ], [ -1, 0, 0, 1/4 ], [ 0, 0, 0, 1 ] ], 
[[ -1, 2, -1, -3/8 ], [ -3/2, 3/2, -1/2, -1/16 ], [ -1/2, 3/2, -3/2, -17/16 ], [ 0, 0, 0, 1 ] ] 
]
```

[The specification](https://www.gap-system.org/Manuals/pkg/cryst/htm/CHAP002.htm) of the above representation of affine transformations is by augmented matrices of the form

                     [ M t ]
                     [ 0 1 ]

which act from the left on column vectors (x,1). Such matrices are said to be affine matrices acting on the left.

I want to know if `spglib` can identify the corresponding space group created by the above generators. I looked through the [example.py](https://github.com/spglib/spglib/blob/develop/python/examples/example.py) and failed to find any applicable clues for the data I posted here.

Regards,
Zhao

**Comment by atztogo** [comment]
Do you mean https://spglib.github.io/spglib/python-spglib.html#get-spacegroup-type-from-symmetry?

**Comment by hongyi-zhao** [comment]
It seems that if there is a document example, I can try my data according to the similar usage.

**Comment by atztogo** [comment]
No example is provided. I think the current documentation gives enough information to give it a try, and then I believe you will see it, although A test exists, https://github.com/spglib/spglib/blob/develop/python/test/test_spacegrouop_type_from_symmetry.py

Docstring also gives more detailed array structures:
```python
In [1]: import spglib

In [2]: help(spglib.get_spacegroup_type_from_symmetry)
```

**Comment by hongyi-zhao** [comment]
I tried as follows, but it fails, and none is returned:
```python
In [1]: import spglib
In [3]: rot=[ [ [ 0, -1, 0 ], [ 0, 0, -1 ], [ -1, 0, 0 ] ], [ [ -1, 2, -1 ], [ -3/2, 3/2, -1/2 ], [ -1/2, 3/2, -3/2 ] ] ]

In [4]: rot
Out[4]: 
[[[0, -1, 0], [0, 0, -1], [-1, 0, 0]],
 [[-1, 2, -1], [-1.5, 1.5, -0.5], [-0.5, 1.5, -1.5]]]

In [5]: tran=[ [ 1/4, 1/4, 1/4 ], [ -3/8, -1/16, -17/16 ] ]

In [6]: spglib.get_spacegroup_type_from_symmetry(rot,tran)
```
In the docstring returned by `help(spglib.get_spacegroup_type_from_symmetry)`, I noticed the following description, which should indicate that this function is not suitable for the data I provide here:

```python
    Parameters
    ----------
    rotations : array_like
        Matrix parts of space group operations.
        shape=(n_operations, 3, 3), order='C', dtype='intc'
```

**Comment by atztogo** [comment]
They have to be in crystallographic basis.

**Comment by hongyi-zhao** [comment]
Just based on the above data provided by me, how can I find an eligible crystallographic basis and then convert my data using it?

Below are some background and additional notes on this issue.

I am currently developing a package for space group structure determination and isomorphism determination between different space groups based on any given set of generators. This data discussed here is generated by my algorithm and they can pass the verification of [BCS IDENTIFY GROUP program](https://www.cryst.ehu.es/cgi-bin/cryst/programs/checkgr.pl?tipog=gesp) as shown below:

1. First, convert the generators of the Space Group to meet the format required by [BCS IDENTIFY GROUP program](https://www.cryst.ehu.es/cgi-bin/cryst/programs/checkgr.pl?tipog=gesp):

```mathematica
In[118]:= MatrixOrder // ClearAll;
MatrixOrder[m_?MatrixQ, maxIter_Integer : 6] := 
 Module[{n = 1, i = IdentityMatrix[Length[m]]}, 
  NestWhile[(n++; m . #) &, m, # != i &, 1, maxIter];
  (*If[n==maxIter,StringForm["Maximum steps exceeded the limit `1`.",
  maxIter],{n}]*)(*{n,n-1==maxIter}*)n]
(*gap>gensSGc2false:=GeneratorsOfGroup(SGc2false);*)
"gensSGc2false:=[[[0,-1,0,1/4],[0,0,-1,1/4],[-1,0,0,1/4],[0,0,0,1]],[[\
-1,2,-1,-3/8],[-3/2,3/2,-1/2,-1/16],[-1/2,3/2,-3/2,-17/16],[0,0,0,1]]]\
" // StringReplace[#, {"[" -> "{", "]" -> "}"}] & // ToExpression
MatrixOrder /@ gensSGc2false[[All, 1 ;; 3, 1 ;; 3]]
Table[(i[[1 ;; 3, 1 ;; 3]] . Transpose[{{x, y, z}}] + 
       i[[1 ;; 3, 4]]) // Transpose, {i, gensSGc2false}] // 
   ArrayFlatten[#, 1] & // ToString[#, InputForm] & // 
 StringReplace[#, {"(" -> "", ")" -> ""}] &

Out[121]= {6, 4}

Out[122]= "{{1/4 - y, 1/4 - z, 1/4 - x}, {-3/8 - x + 2*y - z, -1/16 - \
3*x/2 + 3*y/2 - z/2, -17/16 - x/2 + 3*y/2 - 3*z/2}}"
```

3. Then identify it as follows:

![image](https://user-images.githubusercontent.com/11155854/187825642-bd3602ee-1b87-4cc6-8fb9-54c159db4881.png)
![image](https://user-images.githubusercontent.com/11155854/187825663-0e586ef6-f68d-4855-a30c-49721bb5bdc9.png)

**Comment by atztogo** [comment]
I don't know about gap.

With $\mathrm{L}=(\mathbf{a}, \mathbf{b}, \mathbf{c})$, a rotation in Cartesian and crystallographic coordinates $\mathrm{W}$ and $\boldsymbol{W}$, respectively,

$$
\boldsymbol{W} = \mathrm{L}^{-1} \mathrm{W}  \mathrm{L}.
$$

**Comment by hongyi-zhao** [comment]
> I don't know about gap.

I didn't use GAP for my development, but Mathamatica, and GAP is just an auxiliary validation and research tool in my current situation.

> With $\mathrm{L}=(\mathbf{a}, \mathbf{b}, \mathbf{c})$ , a rotation in Cartesian and crystallographic coordinates W and **W**, respectively,
> $\boldsymbol{W}=\mathrm{L}^{-1} \mathrm{WL}$

You're saying the matrix representations of the same operator under different bases. As you can see, the orders of generators' point group part satisfies the crystallographic restriction theorem. More intriguingly, the identification can be done successfully by the BSC IDENTIFY GROUP tool, as shown in the screenshots posted above.

Therefore, I am still very confused about this question. Does this question involve some subtle differences between the space group and the crystallographic group?

**Comment by atztogo** [comment]
What is implemented in spglib is not in arbitrary setting.

**Comment by hongyi-zhao** [comment]
Thank you for comment and explanation. I see the point: this indicates that these two generators are represented on a basic Cartesian basis rather than a crystallographic basis.

**Comment by atztogo** [comment]
Yes, it's my guess. Internally, spglib transforms the symmetry operations by change-of-basis to a standardized crystallographic basis. Using this matrix representations are transformed to those comparable with the dataset of matrix representations like those found in ITA.

**Comment by hongyi-zhao** [comment]
BTW, how can I input the centered $LaTeX$ formula, as you did [here](https://github.com/spglib/spglib/issues/189#issuecomment-1233713917):

![image](https://user-images.githubusercontent.com/11155854/187841858-5f96f718-e116-4702-9577-d096fd7914fd.png)

**Comment by atztogo** [comment]
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions

**Comment by hongyi-zhao** [comment]
Now, I tried the following space group generators which have pure integer linear (rotation) matrices, but `spglib` still returns nothing:

```python
$ pyenv shell datasci 
$ pip list|grep spglib
spglib                            2.0.1
$ ipython
In [1]: import spglib

In [2]: rot=[ [ [ 0, -1, 0 ], [ 0, 0, -1 ], [ -1, 0, 0 ] ], [ [ 0, 1, 0 ], [ 0, 0, 1 ], [ -1, -1, -1 ] ] ]

In [3]: tran=[ [ 1/4, 1/4, 1/4 ], [ 1, -1, 1 ] ]

In [4]: spglib.get_spacegroup_type_from_symmetry(rot,tran)
```
