### ISSUE TITLE
Export `spglibConfig.cmake`

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#208]
This is needed to import spglib in a cmake project.

For this, the targets should also be exported with appropriate `NAMESPACE`. [Example from `nlopt`](https://github.com/stevengj/nlopt/blob/97a1e789d6e6cd46d94147a8fbcccf2ecb003aac/CMakeLists.txt#L386-L411)

**Comment by atztogo** [comment]
I am not an expert of cmake. Could you explain more?

**Comment by LecrisUT** [comment]
I am not well-versed enough to write up this, but I will try something out when I get the time.

But basically adding a `spglibConfig.cmake` makes it possible to use cmake native commands, i.e. `find_package(spglib)` instead of using `pkg-config` and use the local targets (with additional namespace `spglib::`). [This link](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html) should walk you through the recommended procedure, but I didn't look for an example package to how to set it up.

PS: Also ping the packagers about this change to add the relative files. E.g. Fedora packages lack even the pkg-config files.

**Comment by atztogo** [comment]
@LecrisUT, thanks for your information. I understand the usefulness of spglibConfig.cmake. I will have a look at the link. Right now I don't have enough time to do it, but I will.
