### ISSUE TITLE
niggli_reduce gives a vector along the negative x direction

### ISSUE THREAD

**Issue by nosarthur** [spglib/spglib#211]
## Describe the bug

Often times, space group libraries assume the a vector to be along the positive x direction, if the lattice parameters a, b, c, alpha, beta, gamma are given. However, I notice `niggli_reduce` could return a vector in the negative x direction. If we turn these box vectors into lattice parameters, while keep the atom coordinates unchanged, then we won't be able to reconstruct the unit cell /super cell correctly.

Given that, is it possible to further restraining the returning a vector to be along positive x direction?
## To Reproduce

```
Python 3.8.10 (default, Jun  2 2021, 10:08:05)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from spglib import niggli_reduce

In [17]: box
Out[17]:
array([[ 7.02906765,  0.        ,  0.        ],
       [ 1.52248943, 12.53265392,  0.        ],
       [-8.99996365,  8.37106913, 12.0042361 ]])

In [18]: nbox=niggli_reduce(box)

In [19]: nbox
Out[19]:
array([[ -7.02906765,   0.        ,   0.        ],
       [ -1.52248943, -12.53265392,   0.        ],
       [ -3.49338543,  -4.16158479,  12.0042361 ]])
In [20]: import spglib

In [21]: spglib.__version__
Out[21]: '1.14.1'
```

## Environment

- Python version: 3.8.10
- Spglib's version: 1.14.1

**Comment by atztogo** [comment]
> Given that, is it possible to further restraining the returning a vector to be along positive x direction?

What do you want to make basis vectors like?

**Comment by nosarthur** [comment]
I want the a vector to be along positive x axis. In this example, instead of 

```
array([[ -7.02906765,   0.        ,   0.        ],
       [ -1.52248943, -12.53265392,   0.        ],
       [ -3.49338543,  -4.16158479,  12.0042361 ]])
 ```

return 
```
array([[ 7.02906765,   0.        ,   0.        ],
       [ 1.52248943, 12.53265392,   0.        ],
       [ -3.49338543,  -4.16158479,  12.0042361 ]])
```

My current hack is to check if the new box `nbox[0][0]` is negative, if so, negate the a and b vectors 

  ```
from spglib import niggli_reduce as _niggli_reduce

# TODO: 1.14.1 still could return a vector along negative x axis
def niggli_reduce(box: np.ndarray, eps=1e-5) -> np.ndarray:
    box = _niggli_reduce(box, eps)
    if box[0][0] < 0:
        box[0] = -box[0]
        box[1] = -box[1]
    return box
  ```

**Comment by nosarthur** [comment]
Actually, is the return of `niggili_reduce` guaranteed to be in the lower triangular form? 

In my applications, it seems to be the case, not sure if that's partly because my input boxes are already in the lower triangular form.

**Comment by atztogo** [comment]
What you expect may violate the definition of Niggli cell.

> Actually, is the return of `niggili_reduce` guaranteed to be in the lower triangular form?

I think no.

**Comment by nosarthur** [comment]
I tried random matrices and confirmed that `niggli_reduce` doesn't always return lower triangular form.

I will drop this case since my usage may be too special. Thanks for your help
