### ISSUE TITLE
PyPI build failure on github workflow

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#217]
Wheel build in [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) fails at cmake process.

https://github.com/spglib/spglib/actions/runs/3922329523 (I thought python 3.6 may have problem.)
https://github.com/spglib/spglib/actions/runs/3922368682 (I skipped python 3.6 build, but still fails.)

@LecrisUT, do you have any idea?

**Comment by LecrisUT** [comment]
It seems to fail at the stage of `FindPython` used by `scikit-build`. People from that project [are recommending](https://github.com/scikit-build/scikit-build/issues/840#issuecomment-1380784779) to use `scikit-build-core` moving forward instead. I don't know if that has more fixes that are worth the migration.

One difference between them is that the `scikit-build` scripts build the SOABI (`_spglib.cpython-311-x86_64-linux-gnu.so`), while their recommended version using upstream can only build `_spglib.so`. We had some issues when installing that was looking for the SOABI, but it seems using either `scikit-build` or `scikit-build-core` over plain `setuptools` overcomes that issue (the other 2 simply install anything that's inside `spglib` folder). And realistically, I've tried both executables and they seems to work without the ABI, but I'm not familiar enough with Python to know why the SOABI is introduced.

Anyway, let me try to reproduce this locally and I'll get back to you

**Comment by LecrisUT** [comment]
Oh I have a clue of what's going on. The previous methods were using `python setup.py`, while this one uses the more modern `pyproject.toml`. It seems to detect the cmake arguments well so it does use `setup.py`, but it seems to not play well with other workflows `pyproject.toml`. [An example](https://github.com/scikit-build/scikit-build-core/tree/main/tests/packages/simple_setuptools_ext) for `scikit-build-core` seems to have the project setup a bit differently.

But could all be a red-herring. ~~Back to trying to reproduce this locally.~~ Manged to reproduce it. Debugging time

**Comment by atztogo** [comment]
Solved at #218.
