### ISSUE TITLE
Question about Delaunay and Niggli reductions for layer group

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#222]
Delaunay and Niggli reductions for layer group are implemented. I have a question about how it works.

In both algorithms, we don't want `aperiodic_axis` to join swapping with other basis vectors. So the reduction is performed basis vectors except for the `aperiodic_axis`. What we have to be careful is that the linear combination of the basis vectors will not be parallel to the `aperiodic_axis` during algorithm running.

Is my understanding correct? Ping @site-g.

**Comment by site-g** [comment]
> we don't want `aperiodic_axis` to join swapping with other basis vectors

Current implementation forbids not only swapping but also mixing `aperiodic_axis` into `periodic_axes`. However, mixing `periodic_axes` into `aperiodic_axis` is allowed, i.e. let **c** be the `aperiodic_axis`, **a**' = **a** + **c** is prohibited, **c**' = **a** + **c** is permitted. Then **a**' will never contain **c** while **c**' never loses its **c** component. I think this has eliminated the chance of periodic basis vectors parallel to the `aperiodic_axis`.

> the reduction is performed basis vectors except for the `aperiodic_axis`

No. For Monoclinic/Rectangular system, the 2-fold axis is **a**, the `aperiodic_axis` is **c**. Delaunay reduction is performed between **b** and **c**. As we have discussed in #209. In 3D `delaunay_reduce` for primitive cell, the `aperiodic_axis` also joins the reduction.

I think the effect of the reduction is (**a**', **b**', **c**') = (**a**, **b**, **c**) · **W**, where **W** is one of the following matrices according to which axis is `aperiodic_axis`
![image](https://user-images.githubusercontent.com/35136455/214471073-2a537830-99b4-4b44-8156-3ba07a5bdc98.png)
the subscript **a**, **b** and **c** indicate `aperiodic_axis`, W<sub>ij</sub> are integers.

**Comment by atztogo** [comment]
Thanks @site-g for your clear explanation!
