### ISSUE TITLE
Fortran interface test using ctest

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#225]
As pointed out at #224, we need fortran interface test, which seems reasonably done using ctest. I found [an instruction](https://qiita.com/implicit_none/items/dc83695c301f107dbd6c) though written in Japanese language.

**Comment by LecrisUT** [comment]
Do we want to do it in googletest or native ctest? I could help with the latter.

Can you write some test files of the form:
```fortran
! Filename: my_test.F90
function my_test(argc, argv) result(ret) bind(c)
  use iso_c_binding
  integer(c_int), intent(in) :: argc
  character(kind=c_char), intent(in) ::  argv(argc)
  integer(c_int)   :: ret
  
  ret = 0

end function
```

Then we can hook them seamlessly.

Explanation:
Ctest reads the file name and links the test to a main test executable assuming the name of the function is the ne of the file. The [format of the function](https://cmake.org/cmake/help/latest/command/create_test_sourcelist.html) should be of the equivalent form of a main C file with similar return if succeed or fail, i.e.
```cpp
int main(int argc, char* argv[]]{
  return 0;
}
```

The fortran code just mimics that.

**Comment by atztogo** [comment]
> Can you write some test files of the form?

Yes. Thanks for your help. I will do.
