### ISSUE TITLE
Unify version number between those in CMakeLists.txt and pyproject.toml

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#228]
Currently spglib version number is written in `CMakeLists.txt` and `pyproject.toml`. Can it be unified?

I was looking for a way to do it in `pyproject.toml` under scikit_build_core backend but could not find a solution. So can it be done by `CMakeLists.txt`?

**Comment by LecrisUT** [comment]
On `scikit_build_core` it is in the works [scikit-build-core#116](https://github.com/scikit-build/scikit-build-core/issues/116) and [scikit-build-core#172](https://github.com/scikit-build/scikit-build-core/issues/172), and [relevant branch](https://github.com/scikit-build/scikit-build-core/tree/henryiii/feat/dynversion). I would say to wait for those to land and manually set it in the meantime.

I have considered hackish ways like reading from `pyproject.toml` or vice-versa like creating a `pyproject.toml.in`, but there might be complications with other projects importing `spglib` via `ExternalProject` and equivalents.

**Comment by atztogo** [comment]
That's good news! Then, of course, I follow your idea! Thanks for your information.
