### ISSUE TITLE
Build failure in `fortran_test.c` using Intel compiler `ifort`/`ifx`

### ISSUE THREAD

**Issue by dmt4** [spglib/spglib#234]
## Describe the bug

The cmake build (the only option now it seems) fails with ifort 21.1 for having multiple definitions of main in fortran_test.c.

This compiler message seems important:

ifort: command line warning #10434: option '-nofor_main' use with underscore is deprecated; use '-nofor-main' instead

## To Reproduce

mkdir b
cd b
CC=icc CXX=icpc FC=ifort cmake .. -Dspglib_WITH_Fortran=ON
make

## Expected behavior

Uneventful completion

## Environment

- Spglib's version: commit 1b1729ce79ccadf99d42f0bef4e9b726b4191196 (the latest on devel at time of writing)
- Intel compilers version 2021.1

## Additional context

I suspect the appropriate version of  '-nofor_main'  or actual f main need to be used.

**Comment by LecrisUT** [comment]
That is odd. The warning should be cmake version being a bit old. The error seems something else.

Can you share your cmake version, a more complete log or a copy of your build folder?

**Comment by dmt4** [comment]
Looks like responding to github mail notification does not automatically add a comment here.

On the actual topic, you are right, indeed cmake is rather old, this is on some mid-sized hpc facility.

I've tried building on my local machine which has much more recent packages. The error persists, see the full log. It has two compilations, one with ifort etc.. and the other with the newer icx, icpx and ifx, none successful.

[spglib-intel.log](https://github.com/spglib/spglib/files/10768955/spglib-intel.log)

**Comment by LecrisUT** [comment]
Can you try this branch: https://github.com/atztogo/spglib/tree/fortran-test?

**Comment by dmt4** [comment]
Pretty much the same thing, see attachment.

[spglib-intel1.log](https://github.com/spglib/spglib/files/10769221/spglib-intel1.log)

**Comment by LecrisUT** [comment]
Yeah, I managed to replicate. For some reason intel defines a main function. If you're feeling risky, you could disable the tests sine that is the only part that is affected. I'll try to find a longer term solution.

**Comment by LecrisUT** [comment]
@dmt4 I have uploaded a fix to the branch I previously mentioned. If you want to manually fix this:

https://github.com/atztogo/spglib/commit/cb6546e2d71f87b5b25162ef932c984e2bae30ba

**Comment by dmt4** [comment]
Yes that's an option, I've used the v2.0.2 release which doesn't link it anyway. Thanks for looking into it.

I see two potential solutions, link with:

1. ifx/ifort -nofor-main
2. icc/icx -lifcoremt

I'd think (1) is less fragile than (2) but not sure.

**Comment by LecrisUT** [comment]
2 is counter-productive because the main executable is the one that we compile in `test_fortran.c`. It might break the logic we use to actually run the tests there.

Btw: You might want to try #233 for linking your project to spglib.

**Comment by dmt4** [comment]
Thanks for the prompt response and advise, not a huge fan of cmake so I avoid dealing with it much.

I guess we can consider this issue closed.
