### ISSUE TITLE
Build failure in fortran_test.c with ifort

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#235]
Thanks @dmt4 for reporting the issue #234, and thanks @LecrisUT for taking care of it. Although #234 has been closed, to remember this issue, I would like to open this issue as another thread here for remembering it.

**Comment by LecrisUT** [comment]
I have renamed the previous issue and labeled it. Maybe better to do that for tracking. Can we close this?

**Comment by atztogo** [comment]
Yes.
