### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#237]
- [ ] ~~Migrate the documentation `makefile` to cmake. That is the last component that is not fully covered and automated. This could be as simple as `add_custom_command` although we might find a proper `FindSphinx.cmake` that can be more well supported, e.g. [k0ekk0ek/cmake-sphinx](https://github.com/k0ekk0ek/cmake-sphinx)~~. Automated by Readthedocs. Maybe we can add `Doxygen` documentation though
- [x] Nitpick, move the documentation root from https://spglib.github.io/spglib/ to https://spglib.github.io/
- [x] Dropdown to select specific version, i.e. have `https://spglib.github.io/${version}` for each tagged version #245 
- [x] Use dollarmath over sphinx native
- [x] Migrate to readthedocs #245

**Comment by lan496** [comment]
Also, we will need to migrate sphinx's native math notations to ["dollarmath"](https://myst-parser.readthedocs.io/en/latest/syntax/optional.html#math-shortcuts) in myst for clarity.

**Comment by LecrisUT** [comment]
This can be done with regex find and replace
https://regex101.com/r/VAbgo8/1

**Comment by LecrisUT** [comment]
New thing, we can hook read the docs directly to this repo and it supports versioned format out of the box. Currently the build fails, but once it is working, I'll share a link to a working version

**Comment by lan496** [comment]
@LecrisUT All todos have been done! Can I close this issue?

**Comment by LecrisUT** [comment]
Hmm we have #259 for the doxygen and so I would say sure :+1:
