### ISSUE TITLE
Update conda-forge

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#247]
Will need some help on this one

**Comment by atztogo** [comment]
@jochym, can we invite @LecrisUT to the spglib-feedstock? I don't know how to do it...

**Comment by LecrisUT** [comment]
It's more that I don't know how to manage a conda forge package

**Comment by atztogo** [comment]
The spglib conda-forge packaging is a great contribution from @jochym who is the main maintainer. After set-up properly, many things are automated by conda-forge smithy (https://conda-forge.org/docs/maintainer/infrastructure.html#smithy).

I don't know very much about it, but what I know are:

- recipe `meta.yaml` (https://conda-forge.org/docs/maintainer/adding_pkgs.html#the-recipe-meta-yaml)
- Admin commands on PR or issues (https://conda-forge.org/docs/maintainer/infrastructure.html#admin-web-services)

For example, PR of `meta.yaml` and "@conda-forge-admin, please rerender" updates other files automatically using recipes.

History may be found at
- https://github.com/conda-forge/spglib-feedstock/pulls?q=is%3Apr+is%3Aclosed

I don't know well about `build.sh` and `build.dat` (https://conda-forge.org/docs/maintainer/adding_pkgs.html#optional-bld-bat-and-or-build-sh). I guess this is used to build C-libraries in addition to the python module by `meta.yaml`. We will need to build Fortran libraries as well.

**Comment by LecrisUT** [comment]
Ok, thanks for the tips

**Comment by jochym** [comment]
Welcome @LecrisUT ! Are you willing to co-maintain the package? If so I will add you to the maintainers and you will gain the access to the repo. The job is simple and fairly low-labor. A lot is automated. But there are some non-intuitive things. Please read the maintainer guide on conda forge. 
**First rule:** Never modify the main branch! All work must be done in PRs and forks. Also try to not over-stress the CI system. The substantial amount of compute is donated to c-f and we do not want to lose that.

Just answer yes to my question and I will add you to the group.

**Comment by LecrisUT** [comment]
Ok, I'll help co-maintain, but I could use some help to get started with conda stuff

**Comment by LecrisUT** [comment]
Ok, everything is up and running on the conda side. Waiting for [conda-forge/spglib-feedstock#82](https://github.com/conda-forge/spglib-feedstock/pull/82) to be merged, and do some sanity checks.
