### ISSUE TITLE
Deprecate github.io documentation

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#252]
So far the readthedocs documentation works well, but there are a few situation to test
- [x] Pushing tags. The recent tag `v2.1.0-rc1` did not create a new documentation. Not sure if it is a webhook issue or rtd configuration issue
- [ ] Missing previous documentations. We can add a branch and a few patch versions to push the documentation, but is it worth it? Which version is the documentation well maintained to push?

To migrate we have to:
- [ ] Change the reference in github 
- [ ] Deactivate the github action related to it
- [ ] Change the reference in the source code
- [ ] Change the reference in `PyPI` and `conda`

**Comment by LecrisUT** [comment]
Lol, I have deleted some ill-defined tags and it retrigerred the rtd builds for the tags. So it was just a hickup on rtd side

**Comment by lan496** [comment]
I guess some external projects refer to the GitHub pages' link. So it is polite to redirect GitHub pages to the new Read the Docs pages.

**Comment by LecrisUT** [comment]
I'm only aware of PyPI and conda. But yeah we should be adding a redirect
