### ISSUE TITLE
Unit-test each special condition

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#264]
As per @lan496's comment in #262, the current implementation has special workarounds for each special situation. We should add unit-tests for these individually. @lan496, can you link to an example?

**Comment by lan496** [comment]
Typically, a too distorted crystal structure and a high tolerance value cause difficult situations for symmetry search. For such cases, we need to somehow handle them by adaptively adjusting the tolerance value, ignoring candidates for symmetry operations, etc., which may not be appropriate to call "workarounds". As for the magnetic space group implementation, I simply add a reported structure to the unit tests (for example https://github.com/spglib/spglib/pull/187)

**Comment by LecrisUT** [comment]
Ok, so they are already more or less covered by the unit-tests. The former as well should have a predictable behaviour that can be unit-tested.

**Comment by lan496** [comment]
@LecrisUT Can I close this issue for now?

**Comment by LecrisUT** [comment]
Indeed I'll address it in a testing-framework refactor
