### ISSUE TITLE
[low priority] wrong script in example

### ISSUE THREAD

**Issue by youngjae142** [spglib/spglib#276]
At line 150 in [spglib](https://github.com/spglib/spglib/tree/develop)/[example](https://github.com/spglib/spglib/tree/develop/example)/[python_api](https://github.com/spglib/spglib/tree/develop/example/python_api)/example_full.py
It's not Rutile but MgB2.

**Comment by lan496** [comment]
@ssrokyz Thank you for your report! I have fixed this issue at https://github.com/spglib/spglib/pull/281.
