### ISSUE TITLE
Locating atoms with fractional occupancies after cell standardization

### ISSUE THREAD

**Issue by tirtha-v** [spglib/spglib#310]
I have being working with structures having fractional occupancies in form of  ase atoms object. However, when the structure undergoes cell standardization using the function **spglib.standardize_cell**, it becomes difficult to locate the new position corresponding to each atom as the system undergoes transformation and rotation.  

My approach to this problem was adding tags to individual atoms and linking it to the atomic coordinates , but the tag values disappear after cell standardization since the spglib defined crystal structure (cell) format contains information only about the lattice parameters , new positions and atomic numbers in form of arrays.

Are there any other ways of linking atomic positions to the fractional occupancies?

**Comment by lan496** [comment]
One way will be to use `get_symmetry_dataset` directly. If you assign a unique number for each fractional occupancy to `types`, you can recover these sites in a refined cell via `std_types` as follows:
```python
from spglib import get_symmetry_dataset

a = 4.0
lattice = [
    [0, a / 2, a / 2],
    [a / 2, 0, a / 2],
    [a / 2, a / 2, 0],
]
positions = [
    [0, 0, 0],
    [1 / 2, 1 / 2, 1 / 2],
]
types = [0, 1]

cell = (lattice, positions, types)
dataset = get_symmetry_dataset(cell)

std_lattice = dataset['std_lattice']
std_positions = dataset['std_positions']
std_types = dataset['std_types']

new_cell = (std_lattice, std_positions, std_types)
```

**Comment by tirtha-v** [comment]
Thank you so much! It is easier to keep track of the atoms now.
