### ISSUE TITLE
Kindly request for spglib.1.12.2 

### ISSUE THREAD

**Issue by PolyuWeldingSpock** [spglib/spglib#311]
Hi

I want to request for a source code of spglib.1.12.2. I know this version is kind of old, however, I want to install cp2k v7.1 and it needs spglib.1.12.2.tar.gz. The download url in toolchain of cp2k has been unvalid. Hope someone could helps me. Thanks!

**Comment by LecrisUT** [comment]
Check the tags: https://github.com/spglib/spglib/releases/tag/v1.12.2. Do you need these as release instead?

**Comment by PolyuWeldingSpock** [comment]
Thanks for your reply. These tags help me. I do not need these as release. Very thanks to you!
