### ISSUE TITLE
`example_full` (c_api) fails on arm

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#316]
With the recent tests introduced in #315 I have found that there is a segmentation fault when running `example_full` on `aarch64` (Fedora). Probably macos would have a similar issue if we extended the CI to test for that as well.

**Comment by atztogo** [comment]
@LecrisUT, could you tell me how I can see the log?

**Comment by LecrisUT** [comment]
1. Go to `testing-farm:fedora-38-aarch64` in the CI and open the testing-farm artifacts
2. In there it will show you the failing tests. (Passing tests are also visible if you need them)
3. Can check the [shell script](https://github.com/LecrisUT/spglib/blob/fdaee54b75ba318472e3019fed9177ef6487b624/example/test.sh#L6-L26) for reference about the steps run. E.g. `rlRun "cmake -B ./build"` just does `cmake -B ./build` and you can find in the log as:
   ```
   :: [ 15:52:33 ] :: [  BEGIN   ] :: Running 'cmake -B ./build'
   ```
4. What we are interested in is:
   ```
   :: [ 15:52:34 ] :: [  BEGIN   ] :: Running './build/example_full'
   /usr/share/beakerlib/testing.sh: line 896:  3972 Segmentation fault      (core dumped) ./build/example_full
   :: [ 15:52:34 ] :: [   FAIL   ] :: Command './build/example_full' (Expected 0, got 139)
   ```
   But this doesn't tell much because it segfaults before any print. I probably haven't set it to capture stdout properly

**Comment by atztogo** [comment]
@LecrisUT, I could not understand your test system.

I compiled manually in an old way on my m1 mac (`gcc example.c -I ../../include -L../../lib -l symspg -lm`), but I didn't get segmentation fault.

**Comment by LecrisUT** [comment]
Well, firstly the spglib is compiled as `Release`, so make sure the cmake configuration is similar. Then the gcc on Fedora 38 is gcc-13. I'm not sure if homebrew does something different than fedora. And also the issue is on `example_full.c`.

It might not be reproducible between macos arm and linux arm, but it's worth a shot. We could also add cirrusCI or CircleCI to get a m1 arm and linux arm as well, since those are not available on github action. We would have a more limited resource of that though

**Comment by atztogo** [comment]
The gcc used for my compilation above was not gcc, but clang. Sorry for my confusion. I guess `example_full.c` is written in a bad manner, so It may be easier to find the bug in `example_full.c` by watching the stdout of `./build/example_full` than preparing the environment to reproduce on m1 mac.

**Comment by LecrisUT** [comment]
Because before a `printf` command is executed, I think this is not related to the spglib library, but to the example compilation itself. I will investigate this a bit

**Comment by LecrisUT** [comment]
Well, I've narrowed down the issue to `example_spg_standardize_cell_BCC_prim`

**Comment by LecrisUT** [comment]
@atztogo @lan496 I have found the issue, and indeed it is a bug:
Look at the test that succeeded for `example_spg_standardize_cell_BCC_prim` https://artifacts.dev.testing-farm.io/3f500ac2-7dac-4221-909f-7a1e4f706230/:
<details>

```
*** Example of spg_standardize_cell (BCC primitive) ***:
------------------------------------------------------
VASP POSCAR format: to_primitive=0 and no_idealize=0
1.0
4.000117 0.000000 0.000000
0.000000 4.000117 0.000000
0.000000 0.000000 4.000117
2
Direct
0.500000 0.500000 0.500000
0.000000 0.000000 0.000000
------------------------------------------------------
VASP POSCAR format: to_primitive=0 and no_idealize=1
1.0
4.000000 -0.020000 -0.030000
-0.010000 4.000000 -0.030000
-0.010000 -0.020000 4.000000
2
Direct
0.999000 0.001000 0.001000
0.499000 0.501000 0.501000
------------------------------------------------------
VASP POSCAR format: to_primitive=1 and no_idealize=0
1.0
-2.000058 2.000058 2.000058
2.000058 -2.000058 2.000058
2.000058 2.000058 -2.000058
1
Direct
0.000000 0.000000 0.000000
------------------------------------------------------
VASP POSCAR format: to_primitive=1 and no_idealize=1
1.0
-2.010000 2.000000 2.000000
2.000000 -2.020000 2.000000
2.000000 2.000000 -2.030000
1
Direct
0.002000 0.000000 0.000000
```

</details>

Notice that the first 2 runs are outputting: `num_primitive_atom = 2`, even though in function `sub_spg_standardize_cell`, the size allocation of `pos` and `typ` is of only `1`. Looking at the code, I do not see that `spglib` is trying to re-allocate the memory if `num_atom < n_std_atoms`, nor is there an interface to do so.

**Comment by atztogo** [comment]
@LecrisUT, indeed!

https://github.com/spglib/spglib/blob/9957bfc15e94bc5d1a495d43fb391f0201897f52/example/c_api/example_full.c#L689-L690

`num_atom` in these two lines should be replaced by `num_atom * 4` that is the theoretical upper limit. Should I make a PR? Or could you fix it in #315?

**Comment by LecrisUT** [comment]
I have only doubled it there, if you can add another commit to that pr it would help

**Comment by atztogo** [comment]
> I have only doubled it there, if you can add another commit to that pr it would help

I am not familiar with doing it. Could you tell me one of the best practice?

**Comment by atztogo** [comment]
I think this is fixed by @LecrisUT. I will close this issue. Unless otherwise, please reopen.
