### ISSUE TITLE
primitive_lattice in magnetic Spglib dataset

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#328]
Documentation of `primitive_lattice` in magnetic Spglib dataset is written [here](https://spglib.readthedocs.io/en/latest/magnetic_dataset.html#intermediate-data-in-symmetry-search). For this I have a question. For type-IV magnetic space groups, is an anti-translation contained in its primitive cell? Or is this primitive cell that found for the space group ignoring magnetic moments? I believe the former because of the following code, but I would like to confirm.

The possible basis vectors (pure translations) of this primitive cell are found considering no spin flip translation only.
https://github.com/spglib/spglib/blob/f44a3c52d6eadf1ab96206d283ad00b3f5f07fd0/src/spin.c#L166-L167

**Comment by lan496** [comment]
> For type-IV magnetic space groups, is an anti-translation contained in its primitive cell?

Yes, the spglib's primitive cell contains an anti-translation lattice point.

The following code also checks that the primitive cell is enlarged by considering magmoms in type-IV:
```python
import numpy as np
from spglib import get_magnetic_symmetry_dataset, get_symmetry_dataset

# AFM BCC
lattice = 4 * np.eye(3)
positions = np.array([
    [0, 0, 0],
    [0.5, 0.5, 0.5],
])
numbers = [0, 0]
magmoms = np.array([
    [0, 0, 1],
    [0, 0, -1],
])

dataset = get_symmetry_dataset((lattice, positions, numbers))
mag_dataset = get_magnetic_symmetry_dataset((lattice, positions, numbers, magmoms))

print(np.linalg.det(dataset['primitive_lattice']), np.linalg.det(mag_dataset['primitive_lattice']))
```

**Comment by atztogo** [comment]
Thanks @lan496. Now it is clear.
