### ISSUE TITLE
detecting c3 rotation doesn't seem to work properly? 

### ISSUE THREAD

**Issue by corinwagen** [spglib/spglib#329]
Hi, I just installed ``spglib`` from pypi today, and I'm struggling to assign point groups to molecules with C3 axes.

Here's a snippet that demonstrates the issue, on ammonia (coordinates from CCCBDB, I added the unit cell myself): 

```
import spglib

lattice = [[4.0, 0.0, 0.0], [0.0, 4.0, 0.0], [0.0, 0.0, 4.0]]

# cccbdb ammonia coordinates, checked in Avogadro
points = [
    [0.38503170013427734, 0.22204282879829407, 0.20125585794448853],
    [0.38503170013427734, 0.6666009426116943, 0.0],
    [0.7700634002685547, 0.0, 0.0],
    [0.0, 0.0, 0.0]
]
numbers = [7, 1, 1, 1]
cell = (lattice, points, numbers)
print(spglib.get_spacegroup(cell, symprec=1e-3, angle_tolerance=-1.0, symbol_type=1))
```

The output is ``Cs^1 (6)`` when it should be ``C3v``. Adjusting ``symprec`` and ``angle_tolerance`` doesn't seem to do anything. 

I'm also getting an incorrect answer for benzene: it should be ``D6h``, but I'm getting ``D2h``. (Other molecules are working correctly.) Am I misunderstanding something fundamental here? If so, I'm sorry.

**Comment by atztogo** [comment]
Spglib is the code for crystal. Therefore your basis vectors also have to have at least the same symmetry as your molecule.

**Comment by corinwagen** [comment]
Ok, my bad. I'll use a different library.

**Comment by lan496** [comment]
@corinwagen You may be interested in [pymatgen's PointGroupAnalyzer](https://pymatgen.org/pymatgen.symmetry.html#pymatgen.symmetry.analyzer.PointGroupAnalyzer).
