### ISSUE TITLE
Manual python installation does not install to package folder

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#330]
Observed in #327. It should install to `spglib` package in the install dir.

@lan496 @atztogo  Quick question about #317. Is a bug-fix and not a general convention change?

**Comment by lan496** [comment]
#317 will be classified as the convention change. I think it should be treated in the next minor version (v2.2.0)

**Comment by LecrisUT** [comment]
Ok, if we need to release bug fixes, I will make a release branch and cherry-pick. I don't think we need to release a bug fix just for this issue
