### ISSUE TITLE
spglib-2.1.0 shows warnings when using `get_spacegroup` method but spglib-2.0.2 does not

### ISSUE THREAD

**Issue by wangzyphysics** [spglib/spglib#336]
The spglib is an useful tool to analysis the symmetry information for giving structure.

Here we want to use the spglib to analysis the symmetry info of given structure by `spglib.get_spacegroup` and `spglib.refine_cell` method in some different tolerances including 0.00001, 0.0001, 0.001, 0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, but in spglib-2.1.0, it shows this: 

```
spglib: No point group was found (line 405, /tmp/pip-install-wo87okks/spglib/src/pointgroup.c).
spglib: Attempt 0 tolerance = 1.000000e-03 failed(line 800, /tmp/pip-install-wo87okks/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /tmp/pip-install-wo87okks/spglib/src/pointgroup.c).
spglib: Attempt 1 tolerance = 9.500000e-04 failed(line 800, /tmp/pip-install-wo87okks/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /tmp/pip-install-wo87okks/spglib/src/pointgroup.c).
spglib: Attempt 2 tolerance = 9.025000e-04 failed(line 800, /tmp/pip-install-wo87okks/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /tmp/pip-install-wo87okks/spglib/src/pointgroup.c).
spglib: Attempt 3 tolerance = 8.573750e-04 failed(line 800, /tmp/pip-install-wo87okks/spglib/src/spacegroup.c).
```
but in older version such as spglib-2.0.2, this warning does not show

Here is the structure info and test script which can be used to repeat the warning above:

```
BN
1.0
  2.13478593     -0.00047962     -0.00000019
 -1.06780826      1.84853908     -0.00000019
 -0.00000004     -0.00000007      1.94254452
 B N
 1 1
direct
0.00002343  0.99997657  0.50000000
0.66667658  0.33332342  0.00000000
```
```
import spglib as spg
from ase.io import read

version = ".".join(map(str, spg.get_version()))
print(f"spg version: {version}")

atoms = read("POSCAR")
cell = atoms.cell
position = atoms.get_scaled_positions()
number = atoms.get_atomic_numbers()
print(spg.get_spacegroup((cell, position, number)))
print(spg.get_spacegroup((cell, position, number), 0.00001))
print(spg.get_spacegroup((cell, position, number), 0.0001))
print(spg.get_spacegroup((cell, position, number), 0.001))
print(spg.get_spacegroup((cell, position, number), 0.01))
print(spg.get_spacegroup((cell, position, number), 0.1))
print(spg.get_spacegroup((cell, position, number), 0.2))
print(spg.get_spacegroup((cell, position, number), 0.3))
print(spg.get_spacegroup((cell, position, number), 0.4))
print(spg.get_spacegroup((cell, position, number), 0.5))
print(spg.get_spacegroup((cell, position, number), 0.6))
print(spg.get_spacegroup((cell, position, number), 0.7))
print(spg.get_spacegroup((cell, position, number), 0.8))

```

Is this a bug? or something that i did to occur this? 

Looking forward to a reply, thx~

**Comment by atztogo** [comment]
Please do not use ASE to interface with spglib. ASE Atoms instance is not supported.

**Comment by wangzyphysics** [comment]
thanks for your kind reply, but I don't think the reason is ASE, I have try to deliver the `cell`, `position` and `number` by numpy but the warning still shows.

```
import spglib as spg
from ase.io import read
import numpy as np

version = ".".join(map(str, spg.get_version()))
print(f"spg version: {version}")

cell = np.array([[2.13478593, -0.00047962, -0.00000019],
                [-1.06780826, 1.84853908, -0.00000019],
                [-0.00000004, -0.00000007, 1.94254452]])
position = np.array([[0.00002343, 0.99997657, 0.50000000],
                    [0.66667658, 0.33332342, 0.00000000]])
number = np.array([5, 7])

print(spg.get_spacegroup((cell, position, number)))
print(spg.get_spacegroup((cell, position, number), 0.00001))
print(spg.get_spacegroup((cell, position, number), 0.0001))
print(spg.get_spacegroup((cell, position, number), 0.001))
print(spg.get_spacegroup((cell, position, number), 0.01))
print(spg.get_spacegroup((cell, position, number), 0.1))
print(spg.get_spacegroup((cell, position, number), 0.2))
print(spg.get_spacegroup((cell, position, number), 0.3))
print(spg.get_spacegroup((cell, position, number), 0.4))
print(spg.get_spacegroup((cell, position, number), 0.5))
print(spg.get_spacegroup((cell, position, number), 0.6))
print(spg.get_spacegroup((cell, position, number), 0.7))
print(spg.get_spacegroup((cell, position, number), 0.8))
```
and here is the output

```
spg version: 2.1.0
Amm2 (38)
Amm2 (38)
Amm2 (38)
spglib: No point group was found (line 405, /tmp/pip-install-wo87okks/spglib/src/pointgroup.c).
spglib: Attempt 0 tolerance = 1.000000e-03 failed(line 800, /tmp/pip-install-wo87okks/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /tmp/pip-install-wo87okks/spglib/src/pointgroup.c).
spglib: Attempt 1 tolerance = 9.500000e-04 failed(line 800, /tmp/pip-install-wo87okks/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /tmp/pip-install-wo87okks/spglib/src/pointgroup.c).
spglib: Attempt 2 tolerance = 9.025000e-04 failed(line 800, /tmp/pip-install-wo87okks/spglib/src/spacegroup.c).
spglib: No point group was found (line 405, /tmp/pip-install-wo87okks/spglib/src/pointgroup.c).
spglib: Attempt 3 tolerance = 8.573750e-04 failed(line 800, /tmp/pip-install-wo87okks/spglib/src/spacegroup.c).
Amm2 (38)
P-6m2 (187)
P-6m2 (187)
P-6m2 (187)
P-6m2 (187)
P-6m2 (187)
P-6m2 (187)
P-6m2 (187)
P-6m2 (187)
P-6m2 (187)
```

**Comment by atztogo** [comment]
I could reproduce your issue.

The following line emits the warning, but finally `Amm2 (38)` is found.
`print(spg.get_spacegroup((cell, position, number), 0.001))`

So I think you can safely ignore this warning.

But warning should not be displayed. This is probably due to developer side issue. Thanks for your report!

**Comment by wangzyphysics** [comment]
The `spglib.refine_cell` will also arise this warning which may not influence the results but it would be better without it.

Thanks for your reply~

**Comment by LecrisUT** [comment]
https://github.com/spglib/spglib/blob/9f2d02d8fa045a98af3e5204a63b7fac61c51b5a/CMakeLists.txt#L58

Warnings are on by default. Should reconsider the api if those are genuine warnings that should always be printed. If not, but the user would benefit from it, we can make it conditional depending on environment variable.

**Comment by wangzyphysics** [comment]
Hey guys, are there any new plans to fix this warning?

**Comment by atztogo** [comment]
I think this is default off, but can be made it on by environment variable.

**Comment by atztogo** [comment]
> I think this is default off, but can be made it on by environment variable.

This is what I expect.

**Comment by LecrisUT** [comment]
> Hey guys, are there any new plans to fix this warning?

Can you remind me again over the weekend?

>> I think this is default off, but can be made it on by environment variable.
>
> This is what I expect.

I don't think I've added that for all warnings. Probably should change the macro itself to include such an if statement. At the same time, these are not actual warnings, these are debug messages, so we should go through each one and fix by their intent. Basically:
- if `SPGLIB_WARNINGS=OFF`, no warning messages are compiled
- when `SPGLIB_WARNINGS=ON`, all messages will be checked by `if get_env` and only than it should run
- change the type of message from `warning` to `debug` if it's a debug message and not a warning.

Similarly for `SPGLIB_DEBUG`

**Comment by kavanase** [comment]
Hi @atztogo @LecrisUT, thanks for looking into this!
Just to note, about this point:
> I think this is default off, but can be made it on by environment variable.

It seems the warnings were off by default with `spglib<2.1.0`, but versions since then are showing these warnings, with both the `pip install spglib` and `conda install -c conda-forge spglib` versions. With later versions, warnings like these are encountered (even though the final output is correct):

```
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 0 tolerance = 1.000000e-02 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
spglib: No point group was found (line 405, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/pointgroup.c).
spglib: Attempt 1 tolerance = 9.500000e-03 failed(line 800, /Users/runner/miniforge3/conda-bld/spglib_1707625470649/work/src/spacegroup.c).
```

**Comment by LecrisUT** [comment]
Yeah the default was changed, because I thought those were used for warnings only, but it was used for debug info as well.

A tip, you can add cmake options to `pip install`, e.g.
```console
pip install git+https://github.com/spglib/spglib --config-settings=cmake.define.SPGLIB_WARNING=OFF
```

**Comment by kavanase** [comment]
Ah that's useful to know, thanks!
Though in our case ideally the the user would be able to install our package ([doped](https://doped.readthedocs.io)) with just `pip install`, and from what I can tell these `config-settings` (and github install) can't be easily passed to dependencies (`spglib`) via the `pyproject.toml` config file.

**Comment by LecrisUT** [comment]
Yeah, this is just a temporary hack if you want to test some things. You can always re-install a dependency after you have installed the main project, or in some cases you can chain them, e.g.:
```
pip install foo git+https://github.com/bar/bar --config-settings=...
```
but not sure how well it works with pinned versioned dependencies.

**Comment by LecrisUT** [comment]
@wangzyphysics I am working on #457 if you want to have a look at it.

**Comment by wangzyphysics** [comment]
> @wangzyphysics I am working on #457 if you want to have a look at it.

Thank you for mentioning me, but I'm not very familiar with C language -.-||. I will keep up with your updates.

**Comment by LecrisUT** [comment]
Just reviewing if the messages makes sense as `warning`/`debug`, or trying it out with `pip install` pointing to my fork+branch would be very useful feedback.

**Comment by wangzyphysics** [comment]
> Just reviewing if the messages makes sense as `warning`/`debug`, or trying it out with `pip install` pointing to my fork+branch would be very useful feedback.

I have installed spglib from your branch and now the `warning`/`debug` is gone! Thanks again!
