### ISSUE TITLE
get_magnetic_symmetry_dataset seg fault

### ISSUE THREAD

**Issue by joasode** [spglib/spglib#348]
When I try to get the magnetic dataset with large symprec, I get Segmentation fault (core dumped). It would be desirable to have similar behavior as the ordinary get_symmetry_dataset which returns None.

```
from spglib import get_magnetic_symmetry_dataset
from numpy import logspace
cell = ([[4, 0, 0.0],
         [0, 4, 0.0],
         [0, 0, 18]],
        [[0, 0, 0.57],
         [0.5, 0.5, 0.43],
         [0.5, 1, 0.5],
         [0, 0.5, 0.5]],
        [ 9,  9, 25, 25],
        [ 0,  0, -1,  1])

for symprec in logspace(-5, 1, 13):
    dataset = get_magnetic_symmetry_dataset(cell, symprec=symprec)
    print(dataset)
```

**Comment by lan496** [comment]
Thank you for your report. I have reproduced the segmentation fault with symprec=3.0. 
Although such a large symprec is nonsense, I also think that None should be returned in such a case.

**Comment by lan496** [comment]
I will close this issue because the fix for it is merged in develop branch https://github.com/spglib/spglib/pull/349. Feel free to reopen if the issue still occurs.
