### ISSUE TITLE
Releasing v2.2.0

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#350]
After https://github.com/spglib/spglib/pull/349 is merged, I would like to release the next version possibly v2.2.0.
I think the corrections of Hall symbols (https://github.com/spglib/spglib/pull/317) deserve minor change (v2.2.0), not patch change (v.2.1.1).
@LecrisUT @atztogo do you have any ongoing PRs to be included in the next version?
If not, I will write a release note and a corresponding PR so far.

### Remained TODOs
- [x] https://github.com/spglib/spglib/pull/357
- [x] https://github.com/spglib/spglib/pull/371

**Comment by atztogo** [comment]
Thanks @lan496. From me, nothing. #339 is not urgent.

**Comment by LecrisUT** [comment]
I'll do #341, #349,  and hopefully #257 today (I'll just patch my sphinx theme version in rtd)

**Comment by lan496** [comment]
Thank you both! It will be nice to release the next version after https://github.com/spglib/spglib/pull/257 (improving release docs).   As https://github.com/spglib/spglib/pull/349 is not a critical bug, it is not an urgent matter.

**Comment by LecrisUT** [comment]
Ok, those PRs are ready, but we should wait for sphinx-book-theme to release at least a pre-release, then we can revert https://github.com/spglib/spglib/pull/257/commits/16a1efde2c89cc09bdd57775c85cb1fc541033a2, otherwise PyPI will complain when packaging

**Comment by LecrisUT** [comment]
@lan496 Can you edit your first comment to add #357 as a requirement before the release?

**Comment by lan496** [comment]
@LecrisUT Sure. I've updated.

**Comment by lan496** [comment]
@LecrisUT Sorry for being late in merging https://github.com/spglib/spglib/pull/357. I forgot that PR was ready to be merged.

I will write a release note for the next version just after merging https://github.com/spglib/spglib/pull/371.
