### ISSUE TITLE
Documentation for python returned values

### ISSUE THREAD

**Issue by YKQ98** [spglib/spglib#354]
When I am using python based spglib, I am confused about the rotation matrix returned. For example, for the sym dataset returned rotation matrices R \in R^{3,3}, shall I use it as Rx, where x \in R^3 is a column vector, or shall I use it as xR, where x \in R^3 is a row vector? and Also for the returned std_rotation_matrix Rot \in R^{3,3}, shall I regard it as a left rotation which resulting in (Ra,Rb,Rc) where a,b,c are column lattice vectors, or the right rotation like  (aR,bR,cR) where a,b,c are column vectors? 

This is confusing because L matrix are returned as a row vector based matrix, and also P matrix. But I do not know what rotations means.

**Comment by atztogo** [comment]
The matrix to represent the basis vectors is transposed with respect to the definition in C.
https://spglib.readthedocs.io/en/latest/python-spglib.html#crystal-structure-cell
The convention about rotations is written here,
https://spglib.readthedocs.io/en/latest/definition.html
At least, we can not change the convention of the basis vector matrix from now.

Writing documentation needs a lot of effort. We don't have enough resource to help all the people. If you need documentation, other people may do. It is your turn to help other people. Your contribution is very welcome.

**Comment by YKQ98** [comment]
Sure, I can help and contribute with some documentations. 

Just to confirm, the metrics R, including the rotation metrics representing the space group operations and the std rotation matrix representing the rotation from input lattice to std lattice, are right hand side rotation matrix, and need to apply to a column vector v like Rv instead of vR?

Where shall I add these documentations? I can add them in the code and do a pull request if you prefer.

**Comment by atztogo** [comment]
I think that the answer is written at https://spglib.readthedocs.io/en/latest/definition.html.
Before you start to write documentation, we have to discuss what documentation is needed. Some may be already there, and in that case, we have to consider reorganize the existing documentation. The fist step of the route is raising an issue, where we can discuss how you can help the spglib project.

**Comment by atztogo** [comment]
Maybe you mean you need more information about rotation at https://spglib.readthedocs.io/en/latest/variable.html?

**Comment by YKQ98** [comment]
Thank you, after reading these two documents, I feel that these documents are easy to follow, and my current thought is: 
maybe I can include several concrete examples about the outputs of the function and how to use them, just in one of web pages you shared, and this may be enough for the users to have a better understanding.

**Comment by lan496** [comment]
Can I close this issue?

**Comment by lan496** [comment]
I will close this issue since https://github.com/spglib/spglib/pull/369 followed it. Please reopen this issue if needed.
