### ISSUE TITLE
Drop ASE Atoms-like input for Python interface

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#385]
@atztogo
[As stated in the document](https://spglib.readthedocs.io/en/latest/python-spglib.html#ase-atoms-like-input-is-deprecated), an ASE Atoms-like input is deprecated. I think we can drop it now (even ASE itself does not use this style). This will make it easy to annotate types in Python interface functions.

**Comment by atztogo** [comment]
Yes, let's drop it!
