### ISSUE TITLE
RTD v:latest shows older version in title

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#406]
https://github.com/spglib/spglib/pull/404#issuecomment-1913138747

> @LecrisUT Indeed, but stable points to the new tag. Maybe we can rename stable to latest and latest to develop, wdyt?

**Comment by lan496** [comment]
I've manually built the latest docs but the same.
It may be better to link the stable docs outside since most people install a specific version.

**Comment by LecrisUT** [comment]
I can just rename the docs within rtd, I'll look into that in a few minutes

**Comment by LecrisUT** [comment]
Hmm, seems we cannot rename the automated `latest` and `stable`. What we can do instead is to redirect https://spglib.readthedocs.io to https://spglib.readthedocs.io/en/stable which will always point to the latest tagged verison, and on `latest` use: https://sphinx-version-warning.readthedocs.io/en/latest/ .

Thankfully on the `pyproject.toml` we had the foresight to point it to https://spglib.readthedocs.io

**Comment by LecrisUT** [comment]
Ok, `latest` version now points correctly to the tagged version. I have also migrated the default documentation to `stable`. Do we keep `latest` as is, ro do we disable it and enable `develop` in its place? I don't know if the latter will pick up on tags

**Comment by lan496** [comment]
Nice. Let's keep the `latest` as is.
