### ISSUE TITLE
Check "cell" input signature in python interface

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#412]
As raised in #411, this should be fixed by something like `not isinstance(cell, tuple) and not len(cell) in (3, 4)` as @sphuber suggested.

`cell` is defined at https://spglib.readthedocs.io/en/latest/python-interface.html#crystal-structure-cell. I think `cell` can be given by list or something like that. How should we do? Do you have any idea @lan496, @LecrisUT?

**Comment by lan496** [comment]
I also agree to raise an exception when `cell` has an invalid type. This can be harmlessly done by emitting an exception from `spglib._check`: 
https://github.com/spglib/spglib/blob/63a7a4be586bece7dfc5beb9a40e52d37ff7447e/python/spglib/spglib.py#L1999-L2013
The only thing to be discussed will be a name for the exception. For example `CellError`?

**Comment by LecrisUT** [comment]
Use standard `TypeError` and such. Probably individual for each one. I don't think the user would have much use for a `CellError` there since they are already in charge of the type they pass.

Custom exception would be useful for convergence or internal errors.

**Comment by lan496** [comment]
Indeed. `TypeError` will be appropriate.

**Comment by lan496** [comment]
I'll work on it.
