### ISSUE TITLE
Duplicate rotations in spglib.get_symmetry

### ISSUE THREAD

**Issue by Zhuoying** [spglib/spglib#413]
Hi dear developers,
I recently found an inconsistency in get_symmetry_operations() in pymatgen when I update spglib from **1.16.5** to **2.2.0**(or **2.3.0**).
The details are given in pymatgen issue as linked here [https://github.com/materialsproject/pymatgen/issues/3545](https://github.com/materialsproject/pymatgen/issues/3545 )

I tried a few different versions of pymatgen and spglib and located the issue is caused by spglib. 
My example is here:
```
from pymatgen.ext.matproj import MPRester
from importlib.metadata import version
from pymatgen.analysis.structure_matcher import StructureMatcher
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer
import spglib
from pymatgen.core import Structure

sm=StructureMatcher()

print(f"pymatgen: {version('pymatgen')}")
print(f"spglib: {spglib.__version__}")

mpr=MPRester()
s1=mpr.get_structure_by_material_id("mp-2133",conventional_unit_cell=False)
s2=mpr.get_structure_by_material_id("mp-2133",conventional_unit_cell=True)

for symprec in [1e-5,1e-1]:
    for s in [s1,s2]:
        spg=SpacegroupAnalyzer(structure=s,symprec=symprec)
        print(f"symprec={symprec}")
        print("Space group type:", spg.get_space_group_symbol())
        print("Number of operations:", len(spg.get_space_group_operations())) 
```
When `spglib==1.16.5`, the output is 
```
pymatgen: 2023.12.18
spglib: 1.16.5
symprec=1e-05
Space group type: P6_3mc
Number of operations: 12
symprec=1e-05
Space group type: P6_3mc
Number of operations: 12
symprec=0.1
Space group type: P6_3mc
Number of operations: 12
symprec=0.1
Space group type: P6_3mc
Number of operations: 12
```

When `spglib==2.2.0`, the output is 
```
pymatgen: 2023.12.18
spglib: 2.2.0
symprec=1e-05
Space group type: P6_3mc
Number of operations: 24
symprec=1e-05
Space group type: P6_3mc
Number of operations: 12
symprec=0.1
Space group type: P6_3mc
Number of operations: 24
symprec=0.1
Space group type: P6_3mc
Number of operations: 12
```
Is there any insight you can give on this issue? Thanks in advance!

**Comment by atztogo** [comment]
Please describe your issue using the crystal structure format written at https://spglib.readthedocs.io/en/stable/python-interface.html#crystal-structure-cell.

**Comment by Andrew-S-Rosen** [comment]
@Zhuoying --- it would likely help the spglib developers out if you provide a _minimal_ example that solely depends on spglib.

**Comment by Zhuoying** [comment]
@Andrew-S-Rosen @atztogo Thanks for the notice. I provide a minimal example only using spglib here.

```
import spglib
print (spglib.__version__)

cell=([[1.644551, -2.848447, 0.0], [1.644551, 2.848447, 0.0], [0.0, 0.0, 5.306821]],
 [[0.666667, 0.333333, 0.500548],
  [0.333333, 0.666667, 0.000548],
  [0.666667, 0.333333, 0.879762],
  [0.333333, 0.666667, 0.379762]],
 [1, 1, 2, 2],
 [0.0, 0.0, 0.0, 0.0])

for symprec in [1e-5,1e-1]:
    dataset=spglib.get_symmetry_dataset(cell=cell,symprec=symprec)
    print(f"symprec={symprec}")
    print ("rotations from get_symmetry_dataset: ", len(dataset["rotations"]))
    dct=spglib.get_symmetry(cell=cell,symprec=symprec)
    print ("rotations from get_symmetry dict: ", len(dct["rotations"]))
```
The output is
```
2.2.0
symprec=1e-05
rotations from get_symmetry_dataset:  12
rotations from get_symmetry dict:  24
symprec=0.1
rotations from get_symmetry_dataset:  12
rotations from get_symmetry dict:  24
```

**Comment by Zhuoying** [comment]
Basically, there are duplicates in `spglib.get_symmetry()["rotations"]` for some structures (like the example above).

I tested `spglib==1.16.5`, it does not have this bug.

**Comment by atztogo** [comment]
It is due to the backward incomaptibility.

```
As of version 2.0, the behavior of get_symmetry with zero magmoms (corresponding to type-II MSG) is changed. When all magmoms are zero, the newer get_symmetry returns the same spatial symmetry with time_reversal=True and time-reversal=False. This doubles the size of symmetry operations compared to the previous version.
```

https://spglib.readthedocs.io/en/stable/releases.html#get-symmetry

**Comment by Zhuoying** [comment]
@atztogo Thanks for the quick feedback. 
So for spglib 2.0+, it is safer to use get_symmetry_dataset rather than get_symmetry? If so, I will fix the incompatibility in `pymatgen.symmetry.analyzer` which massively uses spglib.
Thank you again!

**Comment by atztogo** [comment]
I don't know because I don't know what you want to do.

**Comment by lan496** [comment]
@Zhuoying 
If magmom is specified, `get_symmetry` tries to search for time reversal symmetry. If you would like to ignore the time-reversal symmetry, please use `get_symmetry_dataset`. I think pymatgen's SpaceGroupAnalyzer already handles it.
https://github.com/materialsproject/pymatgen/pull/2727
