### ISSUE TITLE
Codecov v4

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#417]
V4 release now requires codecov token: https://github.com/codecov/codecov-action?tab=readme-ov-file#v4-release

Interestingly, forks will continue to work even when they don't have access to the repo's secret token.

@lan496 Could you upload the token to a repository secret as `CODECOV_TOKEN`?

**Comment by lan496** [comment]
Done
![image](https://github.com/spglib/spglib/assets/7272505/6e258257-84cb-429c-9727-4c95dd800835)
