### ISSUE TITLE
Release v2.3.1

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#424]
A few bugfixes:
- #423 
- #421 (fixup: #427) 
- #426

Incidentally, we need #422 to fix the CI as well.

This is all I have on my side that would merit a bugfix release. Any thoughts?

**Comment by lan496** [comment]
Thanks. Nothing in particular from me.

**Comment by atztogo** [comment]
I have nothing. I still have #395 in the back of my mind, but I will have time for it later.

**Comment by LecrisUT** [comment]
Added a quick fixup #427. After that, go ahead and edit the `ChangeLog.md` and tag the release

**Comment by lan496** [comment]
Thanks. I'll work on it this weekend.
