### ISSUE TITLE
Python interface is broken: ModuleNotFoundError: No module named 'spglib._version'

### ISSUE THREAD

**Issue by yurivict** [spglib/spglib#429]
```import spglib``` fails:
```
$ python3.9
Python 3.9.18 (main, Dec 10 2023, 01:22:40) 
[Clang 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1 on freebsd14
Type "help", "copyright", "credits" or "license" for more information.
>>> import spglib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/spglib/__init__.py", line 37, in <module>
    from ._version import __version__, __version_tuple__  # noqa: F401
ModuleNotFoundError: No module named 'spglib._version'
```

This is perhaps due to an older py39-setuptools_scm7-7.1.0, which isn't at the latest version 8.x

This line in ```__init__.py``` is a culprit:
> from ._version import __version__, __version_tuple__  # noqa: F401

Please fix this because many distros have setuptools_scm at 7.x or older.

**Comment by LecrisUT** [comment]
Did you run pip install? Can you give more details on how you are running it and the environment?

I doubt it's setuptool_scm, I can't find anything in the changelog.

**Comment by yurivict** [comment]
No pip install.

I am in the context of FreeBSD ports.

I build the package from the port.
py-spglib works fine when the above culprit line is removed.
There is no module _version under spglib.

**Comment by yurivict** [comment]
I am not sure why the sourcecode has this line, and why does it expect the _version.py module.
What creates this module?

**Comment by LecrisUT** [comment]
It's created when you run `pip install`, it's from `tools.setuptools_scm.write_to`. You can run pip install with build isolation off and/or no index if you don't want to download dependencies from pypi

**Comment by LecrisUT** [comment]
[Here](https://src.fedoraproject.org/rpms/pyproject-rpm-macros/blob/rawhide/f/pyproject_wheel.py#_43)'s a reference of what Fedora does.

**Comment by yurivict** [comment]
I am trying to rebuild with PEP517-compliant tools, and still have the same problem that _version.py isn't created.

Are you able to build spglib when py39-setuptools_scm-6.x is installed?
SCM is what deals with versions in python projects because you chose to use it in pyproject.toml.

I am not sure why do you need to invoke SCM (a messy project that many have problems with) - is version really so critical?
Why don't you just put version into the source code?

**Comment by yurivict** [comment]
All SCM does is assumes that the build is from the Git repository.
All packagers don't (can't) use GIt repo, hence they have to use hacks like you linked above.
SCM is really dysfunctional.

**Comment by LecrisUT** [comment]
The version is in the source after `setuptools_scm` adds the version file, and it does not have to be a git repo, it can use the git archive and the sdist archive from pypi.

Please elaborate on your build script. This project is PEP517 compliant, and you can run `python -m build`. We test that both in ci-build-wheel and when we build the sdist.

**Comment by yurivict** [comment]
> [...] it does not have to be a git repo, it can use the git archive and the sdist archive from pypi.

We use tarball downloaded from GitHub and SCM doesn't work. We have to use an environment variable to override the version because SCM fails to detect it in a tarball.

But this is not the major problem.

The major problem is still what the subject line says: it fails to create _version when setuptools_scm is at 6.x.

Are you able to build with setuptools_scm-6.x ?

**Comment by LecrisUT** [comment]
We use tarballs in fedora as well. It uses `.gitarchival.txt`. You can also use the sdist from PyPI which includes PKG-INFO file.

From the documentation in `6.x` [^1] write_to is still documented, so it should work just fine.

Again please share the build instructions used.

[^1]: https://github.com/pypa/setuptools_scm/tree/645bd2338cb3be52a2a107054f0e68850fa9a17c

**Comment by LecrisUT** [comment]
Looking at https://cgit.freebsd.org/ports/tree/science/py-spglib/Makefile, are you using cmake instead of pip to build and install? The former is insufficient because it does not populate the `.egg-info`. I think there is indeed an issue in the cmake that would need to populate those files, but I don't know if there is a pep517 way to create those, or if that would need to be in scikit-build-cli.

**Comment by yurivict** [comment]
Yes, but when I tried to switch to PEP517 tools (build and install, not pip) - the SCM issue was still present.

(pip can not be used in the package build environment because it downloads files - it is a user-level tool).

**Comment by LecrisUT** [comment]
> (pip can not be used in the package build environment because it downloads files - it is a user-level tool).

Please look at the Fedora implementation [here](https://src.fedoraproject.org/rpms/pyproject-rpm-macros/blob/rawhide/f/pyproject_wheel.py#_43). Those flags ensure you are not downloading packages, specifically `--no-build-isolation`, `--no-deps`/`--no-index`.

> Yes, but when I tried to switch to PEP517 tools (build and install, not pip) - the SCM issue was still present.

Can you show me the commands and output?

**Comment by yurivict** [comment]
[Here](https://freebsd.org/~yuri/py39-spglib-2.3.1-run-version-problem.log) is the problem log when built with PEP517 tools.

**Comment by yurivict** [comment]
(The FreeBSD ports framework is set up to use build and install, not pip.)

**Comment by yurivict** [comment]
```
$ cat /usr/local/lib/python3.9/site-packages/spglib/_version.py
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '2.3.1'
version_tuple = (2, 3, 1)
```

**Comment by yurivict** [comment]
When built with PEP517 tools - _version.py is now present, but doesn't contain the right version variable.

**Comment by LecrisUT** [comment]
> (The FreeBSD ports framework is set up to use build and install, not pip.)

Sure `python -m build` is perfectly fine as well, just saying that `pip` is not a user-only tool.

> When built with PEP517 tools - _version.py is now present, but doesn't contain the right version variable.

I believe that's the same issue you encountered in [scikit-build-core](https://github.com/scikit-build/scikit-build-core/issues/387). Are there any updates of when that will be updated? Otherwise, I suggest applying a patch to change it to:
```python
from ._version import version as __version__
```
