### ISSUE TITLE
Incoherent Wyckoff positions of pyspglib and spglib python modules

### ISSUE THREAD

**Issue by babbyone** [spglib/spglib#441]
I found an incoherence between the result of pyspglib and spglib python modules.
I seems to me that the correct behaviours belong to the spglib module.

Here are the lines for reproducing the issue:

```
import spglib
from pyspglib import spglib as spg
from ase.spacegroup import crystal
a = 4.05
al = crystal('Al', [(0, 0, 0)], spacegroup=225, cellpar=[a, a, a, 90, 90, 90])
spg_symm = spglib.get_symmetry_dataset( (al.cell, al.get_scaled_positions(), al.numbers) )
print(spg_symm['wyckoffs']) 
# => ['a', 'a', 'a', 'a']

spg_symm = spg.get_symmetry_dataset( al )
print(spg_symm['wyckoffs'])
# => ['b', 'b', 'b', 'b']
```

The modules required are:
   - ase==3.22.1
   - spglib==2.3.1
   - pyspglib==1.8.3.1

I suspect a simple indexing issue...

**Comment by LecrisUT** [comment]
Pyspglib uses the older spglib library. Please migrate to the current one.

To confirm, which one is correct? @atztogo can you verify as well?

**Comment by babbyone** [comment]
As reported in the [Bilbao Crystallographic server](https://www.cryst.ehu.es/cgi-bin/cryst/programs/nph-wp-list)
the correct answer is "A" not "B" for an ion in position (0 0 0) for the 225 space-group.
Hence, this line is correct:
``` spg_symm = spglib.get_symmetry_dataset( (al.cell, al.get_scaled_positions(), al.numbers) ) ```
However it is not straightfowardly compatible with the ase library:
``` spg_symm = spglib.get_symmetry_dataset( al ) ``` returns an error.

**Comment by LecrisUT** [comment]
Ok. The ase interface was decided to become deprecated. @lan496 can give more insight on this.

But please migrate and use a minimum version requirement for this case. If you can give more context on your use-case and requirements, maybe we can give some design tips

**Comment by babbyone** [comment]
Oh I see.
So in conclusion, I should use the spglib module that is the correct and latest one,
despite not supporting ase interface.

Thank you for your prompt answers!

**Comment by atztogo** [comment]
> To confirm, which one is correct? @atztogo can you verify as well?

'a' and 'b' are equivalent for space group no. 225. spglib can not distinguish them, although the latest version may try to preserve the position of input crystal structure. User's input is arbitrary, e.g., rigid translation, orientation, change of basis, against which spglib can not read mind of users, at least currently.
