### ISSUE TITLE
Consider using spaces instead of tabs

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#446]
Currently, spaces and tabs are mixed in spglib. It gives me a constant cognitive load every time I open files.
@LecrisUT If you have a strong option, could you introduce a formatter to CMake files?

**Comment by LecrisUT** [comment]
I will try to take a look at cmake-format again to see if the issues I had with it are still relevant, otherwise, I'll edit my ide to be more consistent.

Curious, what files were ill-formated? That would helpme decide if I should change everything to spaces. I thought I've had tabs on everything except for inside documentation blobs.

**Comment by lan496** [comment]
I know it is a kind of preference, but I prefer to replace tabs with 4 spaces (or 2 spaces).

**Comment by LecrisUT** [comment]
I gave `cmake-format` another try and I still don't like the output:
```cmake
  set_target_properties(Spglib_Fortran_tests PROPERTIES OUTPUT_NAME
                                                        test_suite_fortran)

  set_tests_properties(
    ${google_tests}
    PROPERTIES
      LABELS
      "${test_labels}"
      # https://stackoverflow.com/a/77990416
      ENVIRONMENT_MODIFICATION
      "PATH=path_list_prepend:$<JOIN:$<TARGET_RUNTIME_DLL_DIRS:Spglib_tests>,\;>"
  )
```
The property and values should be next to each other like the original:
```cmake
	set_target_properties(Spglib_Fortran_tests PROPERTIES
			OUTPUT_NAME test_suite_fortran
	)
	set_tests_properties(${google_tests} PROPERTIES
			LABELS "${test_labels}"
			# https://stackoverflow.com/a/77990416
			ENVIRONMENT_MODIFICATION "PATH=path_list_prepend:$<JOIN:$<TARGET_RUNTIME_DLL_DIRS:Spglib_tests>,\;>"
	)
```

I will instead try to make my IDE more consistent. Can you give me a screenshot of a ill-formatted file?

**Comment by lan496** [comment]
> Can you give me a screenshot of a ill-formatted file?

I think each file itself is properly formatted. I would rather prefer coherence between files w.r.t. spaces and tabs.
