### ISSUE TITLE
Compillation error in HPC

### ISSUE THREAD

**Issue by skvarjun** [spglib/spglib#456]
I was trying to compile spglib in a HPC cluster. I am getting an error related to `gtest-populate`
.
.
.
.
[ 11%] Creating directories for 'gtest-populate'
[ 22%] Performing download step (git clone) for 'gtest-populate'
-- Had to git clone more than once:
          3 times.
CMake Error at gtest-subbuild/gtest-populate-prefix/tmp/gtest-populate-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/google/googletest'
gmake[2]: *** [CMakeFiles/gtest-populate.dir/build.make:102: gtest-populate-prefix/src/gtest-populate-stamp/gtest-populate-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/gtest-populate.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
.
.
.
.

Can someone comment? Thanks in advance.

**Comment by LecrisUT** [comment]
Sorry this an issue that I didn't test cmake versions properly. A few things you can do:
- `pip install 'cmake>=3.24'`
- git clone gtest and pass `-DFETCHCONTENT_SOURCE_DIR_GTEST=/path/to/gtest`
- disable the tests with `-DSPGLIB_TESTS=OFF`
- go to `test/CMakeLists.txt` and remove the line with `FIND_PACKAGE_ARGS`
