### ISSUE TITLE
Release failure

### ISSUE THREAD

**Issue by LecrisUT** [spglib/spglib#468]
I would have expected a failure to be in `build-wheel` timeout, but instead it happened at `pypa/gh-action-pypi-publish@release/v1`. That is rather frustrating. Not even sure what caused it, I will try to get some insight from `cibuildwheel` since it's mostly on their side. It is weird that it failed for `dist/spglib-2.4.0-cp311-cp311-macosx_10_9_x86_64.whl` but not `dist/spglib-2.4.0-cp310-cp310-macosx_10_9_x86_64.whl` If the artifacts are otherwise good, we can download them and upload manually + generate the release manually.

**Comment by LecrisUT** [comment]
@lan496 Can you run the `twine upload` manually?
- Download the artifacts from: https://github.com/spglib/spglib/actions/runs/8647336672/attempts/1
  - `cibw-*` except `cibw-wheels-macOS-11-2`
  - `Packages`
- Extract everything in a `dist` folder (except `Packages`, only extract `spglib-2.4.0.tar.gz`)
- Run `twine check dist/*` and make sure there are not failures
- Run `twine uploade dist/*` with appropriate credentials and project name

I can generate the release after that

**Comment by LecrisUT** [comment]
Haha, I've managed to fix it, by deleting the artifact :tada:

@lan496 Please wait for any PR to merge, probably #471 before we publish the release, I want to avoid errors coming from https://github.com/scikit-build/scikit-build-core/issues/695 later on (sadly conda is affected, because they are using tags instead of releases)

**Comment by lan496** [comment]
@LecrisUT Looks like you have solved everything while I was sleeping 😳

Let me confirm the status. Now [v2.4.0](https://pypi.org/project/spglib/) has been released in PyPI, ~~and we are waiting for #471 before publishing the release note and merging any other PRs~~.

The release note is already published https://github.com/spglib/spglib/releases/tag/v2.4.0

**Comment by LecrisUT** [comment]
Yeah, things got chaotic there a bit, but Henry helped a lot to get things settled.
