### ISSUE TITLE
Deprecated functions in example_full.c

### ISSUE THREAD

**Issue by crystalfp** [spglib/spglib#474]
Started learning the library. Compiled examples using:
```
cd test/example/c_api
gcc example_full.c -I../../../include -L ../../.. -lsymspg -lm -o ex
```
Gives the following deprecation warnings:
```
example_full.c: In function ‘example_spg_get_international’:
example_full.c:272:9: warning: ‘spg_get_international’ is deprecated: Use the variables from SpglibDataset (spacegroup_number, international_symbol) [-Wdeprecated-declarations]
  272 |         spg_get_international(symbol, lattice, position, types, num_atom, 1e-5);
      |         ^~~~~~~~~~~~~~~~~~~~~
In file included from example_full.c:3:
../../../include/spglib.h:398:13: note: declared here
  398 | SPG_API int spg_get_international(char symbol[11], double const lattice[3][3],
      |             ^~~~~~~~~~~~~~~~~~~~~
example_full.c: In function ‘example_spg_get_schoenflies’:
example_full.c:291:5: warning: ‘spg_get_schoenflies’ is deprecated: Use the variables from SpglibDataset (spacegroup_number, international_symbol) [-Wdeprecated-declarations]
  291 |     spg_get_schoenflies(symbol, lattice, position, types, num_atom, 1e-5);
      |     ^~~~~~~~~~~~~~~~~~~
In file included from example_full.c:3:
../../../include/spglib.h:414:13: note: declared here
  414 | SPG_API int spg_get_schoenflies(char symbol[7], double const lattice[3][3],
      |             ^~~~~~~~~~~~~~~~~~~
example_full.c: In function ‘example_spg_get_multiplicity’:
example_full.c:346:5: warning: ‘spg_get_multiplicity’ is deprecated: Use the variables from SpglibDataset (n_operations) [-Wdeprecated-declarations]
  346 |     int size = spg_get_multiplicity(lattice, position, types, num_atom, 1e-5);
      |     ^~~
In file included from example_full.c:3:
../../../include/spglib.h:384:13: note: declared here
  384 | SPG_API int spg_get_multiplicity(double const lattice[3][3],
      |             ^~~~~~~~~~~~~~~~~~~~
example_full.c: In function ‘example_spg_get_symmetry’:
example_full.c:372:5: warning: ‘spg_get_symmetry’ is deprecated: Use the variables from SpglibDataset (rotations, translations) [-Wdeprecated-declarations]
  372 |     int size = spg_get_symmetry(rotation, translation, max_size, lattice,
      |     ^~~
In file included from example_full.c:3:
../../../include/spglib.h:278:13: note: declared here
  278 | SPG_API int spg_get_symmetry(int rotation[][3][3], double translation[][3],
      |             ^~~~~~~~~~~~~~~~
example_full.c: In function ‘show_layer_spg_dataset’:
example_full.c:635:5: warning: ‘spg_get_layer_dataset’ is deprecated: Experimental interface. May be removed in next major release. [-Wdeprecated-declarations]
  635 |     dataset = spg_get_layer_dataset(lattice, position, types, num_atom,
      |     ^~~~~~~
In file included from example_full.c:3:
../../../include/spglib.h:242:24: note: declared here
  242 | SPG_API SpglibDataset *spg_get_layer_dataset(
      |                        ^~~~~~~~~~~~~~~~~~~~~
```
I easily can silence the warnings using `-Wno-deprecated-declarations` but someone that wants to learn the library needs a clean example of usage.
Thanks for considering!
mario

**Comment by LecrisUT** [comment]
Firstly it is recommended to use the CMake build system (or even any build system: `meson`, etc.) so that you have more control over the `spglib` version. Supporting plain compiler compilation will be a nightmare for us if we want to introduce some simple third-party dependencies so that we don't have to re-invent wheels.

As for the examples inside, indeed it might be helpful to remove the deprecated interface. Basically most of those interfaces are deprecated because you might be running `*_get_dataset` multiple times internally, when instead you can run it only once and get all of the data you want from there. Currently that is the preferred interface where the user takes ownership of the dataset to initialize and free it.

If you can make a PR to make the example more concise, that would be much appreciated.

**Comment by crystalfp** [comment]
I agree that CMake is needed to build the library. I was just experimenting because the final use of the library will be inside NodeJS that has its way to build plugins (GYP).

**Comment by LecrisUT** [comment]
Interesting. Can you elaborate on that? Is the plan to create a JavaScript api for Spglib, and if so, can you share a small scriplet of how that works? If it's viable it could be integrated directly.

**Comment by crystalfp** [comment]
Sure! Let me find time to change my application (currently it exec KPLOT executable). For now I'm able to compile and link under Windows using MinGW.

**Comment by LecrisUT** [comment]
Btw, I was planning to package spglib for vcpkg. Would that be useful? How do vcpkg, mingw, etc. differ and/or do you know of forums where to ask these things?

**Comment by crystalfp** [comment]
Successfully integrated spglib in my application (electronjs+vue+typescript on Windows). If could be useful to others, here some points of interest:
- Compile spglib using cmake (for msvs, not MinGW)
- Install the interface packages `npm i -D node-addon-api node-gyp`
- Prepare the interface file that convert NodeJS in/out variables
- Modify `binding.gyp` to link symspg.lib
- Compile and link the Node addon using `npx node-gyp rebuild`
That's all. If you want I can send you the relevant files. Again thanks for the library!

**Comment by LecrisUT** [comment]
I would need some guidance to understand how node packaging works, mostly does it have architecture dependent packages like wheel on PyPI, and if we can build and distribute a package as `npm install spglib`.

> If you want I can send you the relevant files. 

If you can make a gist that would be wonderful

My main worry there is if it's machine dependent or can it be made portable. I think the C# packaging would also help in understanding these environments.
