### ISSUE TITLE
libsymspg.a could not be produced

### ISSUE THREAD

**Issue by alas-go** [spglib/spglib#475]
Dear Developers.
 On Ubuntu 22.04 LTS with cmake 3.29, libsymspg.a  could not be produced by compiling spglib development version using cmake method. Could you help me?

The compiling is below:
mdkir build
 cmake -DCMAKE_INSTALL_PREFIX=/home/adm/spglib-dev/  \
-DSPGLIB_USE_OMP=OFF \
-DSPGLIB_WITH_Fortran=ON \
 ..
 cmake --build .
 cmake --install . --prefix /home/adm/spglib-dev

**Comment by LecrisUT** [comment]
The options are available in the top-most `CMakeLists.txt`. You want `-DSPGLIB_SHARED_LIBS=OFF`

https://github.com/spglib/spglib/blob/5c7046bae1bfcf3c203f7af55d5ad0cfa23161dc/CMakeLists.txt#L53-L62

**Comment by alas-go** [comment]
It is OK after -DSPGLIB_SHARED_LIBS=OFF
Thanks very much
