### ISSUE TITLE
Python get_magnetic_spacegroup_type_from_symmetry

### ISSUE THREAD

**Issue by bpuchala** [spglib/spglib#482]
Thanks for the great package!

Are there any plans to add ``get_magnetic_spacegroup_type_from_symmetry`` to the Python interface? It looks like the corresponding C function [exists](https://github.com/spglib/spglib/blob/69da2b8dc41ea13911cff7879ba9d11a85ae5834/src/spglib.c#L597).

**Comment by lan496** [comment]
I just forgot to port `spg_get_magnetic_spacegroup_type_from_symmetry` to the Python interface 🤔
I will work on this if the function helps Python-interface's users.
