### ISSUE TITLE
Segmentation fault if sym_reduce_operation() fails

### ISSUE THREAD

**Issue by NewSigma** [spglib/spglib#483]
In rare cases, sym_reduce_operation() may fail and return a null pointer.  If this occurs, search_hall_number() will dereference the null pointer and a segmentation fault is triggered.

https://github.com/spglib/spglib/blob/e6bdd0bafcb60ff26c7ce9ff95d13c43e56d995f/src/spacegroup.c#L800-L806

I propose the following code as a suggestion for improvement:

```
    sym_reduced = sym_reduce_operation(primitive->cell, symmetry, tolerance, angle_tolerance);
    if (sym_reduced) { // Avoid dereference null pointer
        hall_number = search_hall_number(origin_shift, conv_lattice, candidates,
                               num_candidates, primitive, sym_reduced, symprec);
        sym_free_symmetry(sym_reduced);
        sym_reduced = NULL;
    }
```

Please let me know if I was wrong. Thank you.

**Comment by lan496** [comment]
Thank you for your careful catch. I will fix the codes from your suggestion.
BTW, how do you find this bug? Do you have some example to cause the segmentation fault?

**Comment by NewSigma** [comment]
Thank you for your comment @lan496.
We have a high-throughput crystal structure prediction program that interfaces with spglib. The program crashes in rare cases because of the segmentation fault. Unfortunately, bad structures are discarded during the searching and I'm afraid I cannot provide examples to cause the segmentation fault.
