### ISSUE TITLE
dataclass output for Python API

### ISSUE THREAD

**Issue by lan496** [spglib/spglib#491]
We start using `dataclasses.dataclass` for some outputs of Python API.

- https://github.com/spglib/spglib/pull/485
- https://github.com/spglib/spglib/pull/490

**Comment by lan496** [comment]
@LecrisUT What do you think about output dictionary of other functions with symmetry operations?
For example, `get_symmetry` returns dictionary keys
```
- rotations
- translations
- (if magmoms specified) time_reversals
- equivalent_atoms
```
and `get_symmetry_from_database` returns
```
- rotations
- translations
```
They are not so coherent to integrate with a single dataclass...

**Comment by LecrisUT** [comment]
These should be deprecated. The data is in `dataset` already. But they should be organized as a class, let's discuss that one in #489

**Comment by LecrisUT** [comment]
Closing this since the main PRs are merged
