### ISSUE TITLE
spg_standardize_cell changes the atoms topology

### ISSUE THREAD

**Issue by crystalfp** [spglib/spglib#493]
I'm using spglib 2.3.2 from C on windows.

Seems spg_standardize_cell not only changes the cell and swap Y and Z axis, but changes also the atoms' topology.

This is the structure before standardization:
![before-standardizing](https://github.com/spglib/spglib/assets/865866/2692a3cd-4a92-462d-b229-2be5b981d6b5)
And this is after standardization:
![after-standardizing](https://github.com/spglib/spglib/assets/865866/fe1e2891-97ab-4387-a759-8349a5f375e4)
And nothing changes for any combinations of to_primitive, no_idealize and symprec.

You see the mutual position of two atoms is drastically different compared to the input structure. Here the code extracted from example_full.c that show the problem.
[standardize.zip](https://github.com/spglib/spglib/files/15343409/standardize.zip)

Is there something I don't understand? Or is it a bad behavior?
Thanks for clarifying!
mario

**Comment by atztogo** [comment]
What do you mean "changes also the atoms' topology."?

**Comment by crystalfp** [comment]
I mean that in the "before" configuration the atoms are positioned in two pairs. In the "after" configuration one pair is way more distant. One user of my application (a crystallographer) said this should never happen. I'm a computer scientist, but understand that it is OK to change the cell and the axis, but moving the atoms in another position (besides small adjustments) change the structure the user is studying.

**Comment by atztogo** [comment]
I consider this is not a problem.

**Comment by LecrisUT** [comment]
As a sanity check, if you make a supercell, can you rotate one to match the other? What rotation, translation and cell change would have been done there?

**Comment by LecrisUT** [comment]
The part that is suspicious to me is the swapping of y and z axis. How did you check that to be the case? @atztogo that should not be allowed to happen right? It would be like switching the chirality of a molecule (easier to word and visualize than in a crystal)

PS: please upload your example in https://gist.github.com

**Comment by atztogo** [comment]
>that should not be allowed to happen right?

It should not happen in spglib.

**Comment by crystalfp** [comment]
Before spg_standardize_cell the atoms fractional coordinates are (line start with the atomic number):
5: 0.0000 0.0000 0.5000
5: 0.3333 0.6667 0.0000
7: 0.0000 0.0000 0.0000
7: 0.6667 0.3333 0.5000

After they are:
5: 0.0000 0.5000 0.0000
5: 0.3334 0.0000 0.6667
7: 0.0000 0.0000 0.0000
7: 0.6666 0.5000 0.3333

A clear swap of Y and Z coordinates.

Before the unit cell vectors (lattice) are:
2.51 0 0
-1.255 2.17372 0
0 0 6.69

After they are:
2.17372 0 -0.918724
0 6.69 0
0 0 2.51

I'm in the middle between the scientists and the library trying to find where I made a mistake or misunderstood the documentation. Thanks for your patience!

**Comment by LecrisUT** [comment]
> PS: please upload your example in https://gist.github.com/

This would help a bunch. It's also good etiquette towards security conscious people.

**Comment by crystalfp** [comment]
[red face] Sorry for the noise. Found the problem. Was using the wrong lattice in output...

The example was: https://gist.github.com/crystalfp/b613861dbe600e79b2d45bc24faef5e4

**Comment by LecrisUT** [comment]
Can you elaborate? Was it a column/row major issue? The only thing I was able to see was:
https://gist.github.com/crystalfp/b613861dbe600e79b2d45bc24faef5e4#file-standardize-c-L44

But that would be a transposition issue which I don't see there.

It would also help figure out what common pitfalls there are and if they can be resolved with more intuitive or careful documentation

**Comment by crystalfp** [comment]
Was entirely my fault. The library was perfect. I forgot that spg_standardize_cell modifies lattice so I copied in output the original lattice, not the standardized one. Sorry again.

**Comment by LecrisUT** [comment]
The gist there is after the correction? The original did not copy `lattice` to `lat`?

**Comment by crystalfp** [comment]
No, the problem was in my code, the one I used to produce the screenshots.
