### ISSUE TITLE
Different spg_standardize_cell results from Python and C

### ISSUE THREAD

**Issue by crystalfp** [spglib/spglib#494]
When running on the same data `spg_standardize_cell` (C) and `spglib.standardize_cell` (Python) the results are different.

In the attached example the resulting lattice is:
```
     7.2552211357743630    0.0000000000000000    0.0000000000000000
    -3.6276105678871815    6.2832058136543862    0.0000000000000000
     0.0000000000000000    0.0000000000000000    5.7126349999999997
```
from Python and:
```
6.283219 0.000000 -2.655613
0.000000 5.712635 0.000000
0.000000 0.000000 7.255212
```
from C. Ignoring the shuffling of coordinates and basis, there is one value quite different.
Instead the fractional coordinates are the same (again considering the basis shuffle between the two languages).

Apparently this is the root of my problems. If the lattice is different, but the atoms fractional coordinates do not change, the relative position of atoms in Cartesian coordinates are different from the two languages and this is not good (as my user diplomatically said).

What I'm missing in the C version to have the same results as from Python? Thanks!

To reproduce (I'm on Window, but the result is the same on Linux):
1. Unzip the attached file after renaming it to `example.zip`
[example.txt](https://github.com/user-attachments/files/15605281/example.txt)

2. Install Python libraries `spglib` and `ase`
3. Run `python main.py` and obtain `outputPOSCAR` file.
4. Build the C example version: `cmake . -B ./build` and `cmake --build ./build`
5. Run it ` .\build\Debug\example.exe` and look at the standard output

**Comment by atztogo** [comment]
We cannot provide support for scripts that use external libraries such as ASE or pymatgen.

Instead, please use the following crystal structure format in python
https://spglib.readthedocs.io/en/stable/python-interface.html#crystal-structure-cell

**Comment by LecrisUT** [comment]
@crystalfp could you upload the contents of the zip to https://gist.github.com

**Comment by crystalfp** [comment]
The Zip content is on [gist](https://gist.github.com/crystalfp/d258b1b168dd35b7f7a6b3823c12d1b0)
The main.py now is library free and the results are on the stdout. 
Thanks for your help!

**Comment by LecrisUT** [comment]
I think you are hitting the same issue as #492, i.e. in python it's a list of lattice-vectors, and in C it's a 3x3 lattice-matrix (i.e. the lattice vectors or arranged on the columns). It is very counterintuitive to have this discrepancy, but we should gather some more ideas on what a reasonable interface for this could be, since both interpretations are perfectly reasonable if you spend some time deliberating it.

**Comment by crystalfp** [comment]
You are right! Transposing the lattice matrix in C generates the same results as Python. Thanks!
And this is clear in the https://spglib.readthedocs.io/en/stable/python-interface.html#crystal-structure-cell page you sent me. Maybe highlighting this fundamental difference in the documentation could help.
Now my job will be to understand who should transpose the matrix, my C application or the user Python application...
Thanks again!
mario
