### ISSUE TITLE
How to find symmetry operations along a specific crystallographic direction in an FCC lattice?

### ISSUE THREAD

**Issue by hongyi-zhao** [spglib/spglib#502]
Hi spglib developers,

I am currently working with a face-centered cubic (FCC) lattice and I need to identify the symmetry operations that preserve a specific crystallographic direction, specifically the [110] direction.

Here is the code I have been using:

```python
import spglib
import numpy as np
from ase.build import bulk

# Use ASE to create the FCC lattice
a = 5.431
fcc = bulk('Cu', 'fcc', a=a)  # Using copper (Cu) as an example, you can replace it with other elements

# Get crystal structure information from ASE
lattice = fcc.get_cell()
positions = fcc.get_scaled_positions()
numbers = fcc.get_atomic_numbers()

cell = (lattice, positions, numbers)

# Get symmetry operations
dataset = spglib.get_symmetry_dataset(cell)
rotations = dataset['rotations']
translations = dataset['translations']

# Specify the crystallographic direction
direction = np.array([1, 1, 0])  # Along [110] direction

# Find symmetry operations that preserve the specified direction
symmetry_operations = []
for rotation, translation in zip(rotations, translations):
    transformed_direction = np.dot(rotation, direction)
    if np.allclose(transformed_direction, direction):
        symmetry_operations.append((rotation, translation))

# Output the results
print("Symmetry operations along the specified direction:")
for rotation, translation in symmetry_operations:
    print("Rotation:")
    print(rotation)
    print("Translation:")
    print(translation)
    print()
```

The result of the above code is as follows:

```
Symmetry operations along the specified direction:
Rotation:
[[1 0 0]
 [0 1 0]
 [0 0 1]]
Translation:
[0. 0. 0.]

Rotation:
[[0 1 0]
 [1 0 0]
 [0 0 1]]
Translation:
[0. 0. 0.]
```

However, I am not sure if this is the correct approach or if there are any specific functions in spglib that can directly provide the symmetry operations along a given direction.

Could you please provide guidance or suggestions on how to correctly identify these symmetry operations?

Thank you for your assistance!

Best regards,
Zhao

**Comment by atztogo** [comment]
Please do not use ASE to describe your example.

**Comment by hongyi-zhao** [comment]
1. Why?
2. Then, what should I use?

**Comment by atztogo** [comment]
1. To reproduce.
2. You can explicitly specify `lattice`, `positions`, `numbers`.

**Comment by atztogo** [comment]
Please use discussion, https://github.com/spglib/spglib/discussions.

**Comment by LecrisUT** [comment]
@hongyi-zhao for context, having direct values makes it easier to follow and guarantees there is no changes in versions of the third-party library. You can add some `assert` and comparisons for `ase` to indicate they are equivalent or where you initially took the values from.

**Comment by hongyi-zhao** [comment]
@atztogo @LecrisUT Thank you for the prompts and opinions. I will try my best to follow them to communicate better.

I have reposted the discussion here: https://github.com/spglib/spglib/discussions/503
