### ISSUE TITLE
Could not run Example.py

### ISSUE THREAD

**Issue by FabriceOE** [spglib/spglib#512]
(disclaimer I am very new to this, so it may be an obvious issue)

*I have a Python3 virtual env inside an Ubuntu machine
* python3 -V    -> Python 3.10.12
* pip list
Package    Version
---------- -------
numpy      2.0.0
pip        22.0.2
setuptools 59.6.0
spglib     2.5.0

--> python3 example.py 

[get_spacegroup]
  Spacegroup of Silicon is Fd-3m (227).

[get_spacegroup]
Traceback (most recent call last):
  File "**********/Symetry_venv/example/example.py", line 159, in <module>
    % spglib.get_spacegroup(silicon_ase)
  File "**********/Symetry_venv/sym_env/lib/python3.10/site-packages/spglib/spglib.py", line 1075, in get_spacegroup
    dataset = get_symmetry_dataset(
  File "**********/Symetry_venv/sym_env/lib/python3.10/site-packages/spglib/spglib.py", line 914, in get_symmetry_dataset
    lattice, positions, numbers, _ = _expand_cell(cell)
  File "**********/Symetry_venv/sym_env/lib/python3.10/site-packages/spglib/spglib.py", line 2065, in _expand_cell
    lattice = np.array(np.transpose(cell[0]), dtype="double", order="C")
TypeError: 'Atoms' object is not subscriptable

And so far I am stuck there
(I tried downgrading numpy to 1.26.4 but it did not help)

Thanks for you help, 
 Fab. O

**Comment by LecrisUT** [comment]
What is the `example.py` pointing to there? The path does not look to point to [`example/python_api/example.py`](https://github.com/spglib/spglib/blob/develop/test/example/python_api/example.py) that we have.

**Comment by FabriceOE** [comment]
I have copied 'Atoms.py' and 'example.py' in a folder 'example'
The "Symetry" folder is  which is on my desktop


* source sym_env/bin/activate

*(sym_env) XXXXX@box:~/Desktop/Symetry_venv$ ls
example  help  log  __pycache__  sym_env  test.py

*(sym_env) XXXXX@box:~/Desktop/Symetry_venv$ ls example/
atoms.py  example.py  __pycache__


(sym_env) XXXXX@box:~/Desktop/Symetry_venv$ python3 example/example.py 

will get you the error above...


Maybe I am just not loading the atoms.py correctly ?

**Comment by LecrisUT** [comment]
Step back a bit, what `example` folder are you referring to. Are you referring to the `example` folder in this project? If so what version did you download/git clone? If not what project are you referring to?

**Comment by FabriceOE** [comment]
I suppose this is the issue here

I directly download the "example" folder from the git, however my install  is *not* a clone from git

It is simply  a "fresh" python3 venv (follow by  "pip install spglib") and I try to run it from there.

**Comment by FabriceOE** [comment]
Btw, thank you for the swift reply, much appreciated :-)


Further info : using the "ase" lib ( pip install --upgrade ase), still inside my venv
I switch to the "atoms from ASE" in the example.py using 

"from ase import Atoms" 

I get a variant error  

[get_spacegroup]
Traceback (most recent call last):
  File "/home/XXXXX/Desktop/Symetry_venv/example/example.py", line 159, in <module>
    % spglib.get_spacegroup(silicon_ase)
  File "/home/XXXXX/Desktop/Symetry_venv/sym_env/lib/python3.10/site-packages/spglib/spglib.py", line 1075, in get_spacegroup
    dataset = get_symmetry_dataset(
  File "/home/XXXXX/Desktop/Symetry_venv/sym_env/lib/python3.10/site-packages/spglib/spglib.py", line 914, in get_symmetry_dataset
    lattice, positions, numbers, _ = _expand_cell(cell)
  File "/home/XXXXX/Desktop/Symetry_venv/sym_env/lib/python3.10/site-packages/spglib/spglib.py", line 2065, in _expand_cell
    lattice = np.array(np.transpose(cell[0]), dtype="double", order="C")
TypeError: float() argument must be a string or a real number, not 'Atom'

**Comment by FabriceOE** [comment]
(with the correct path)

The initial error in "example.py" is  with the bundled "atoms.py" is  ("from atoms import Atoms")


[get_spacegroup]
  Spacegroup of Silicon is Fd-3m (227).

[get_spacegroup]
Traceback (most recent call last):
  File "/home/XXXXX/Desktop/Symetry_venv/example/example.py", line 159, in <module>
    % spglib.get_spacegroup(silicon_ase)
  File "/home/XXXXX/Desktop/Symetry_venv/sym_env/lib/python3.10/site-packages/spglib/spglib.py", line 1075, in get_spacegroup
    dataset = get_symmetry_dataset(
  File "/home/XXXXX/Desktop/Symetry_venv/sym_env/lib/python3.10/site-packages/spglib/spglib.py", line 914, in get_symmetry_dataset
    lattice, positions, numbers, _ = _expand_cell(cell)
  File "/home/XXXXX/Desktop/Symetry_venv/sym_env/lib/python3.10/site-packages/spglib/spglib.py", line 2065, in _expand_cell
    lattice = np.array(np.transpose(cell[0]), dtype="double", order="C")
TypeError: 'Atoms' object is not subscriptable

**Comment by LecrisUT** [comment]
`spglib.get_spacegroup(silicon_ase)` is not supported anymore. The issue is the version of `example.py` is likely outdated, see the file I've linked before, which points to the latest version of the examples. You can make it work by constructing a tuple of `(lattice, position, types)` from the `silicon_ase`.

My recommendation is to get an IDE like VSCode or PyCharm, and navigate the files. They will highlight typing issues and help you with documentation of the API.

**Comment by FabriceOE** [comment]
You are correct there are several "example" folders.... I admit I am a bit lost to why. 

" https://github.com/spglib/spglib/blob/develop/test/example/python_api/example_full.py " --> works !

' https://github.com/spglib/spglib/blob/master/python/examples/example.py '--> does not work (see above)

maybe there could be a "version  XXXX " on the example file to help the inattentive  user :-)

**Comment by FabriceOE** [comment]
Thank you again for your help !  (problem sovled)

**Comment by LecrisUT** [comment]
Aaah, I've found the issue. The `master` branch is *dead*, `devel` is the actual `main` branch. @lan496 @atztogo can we delete: `rc`, `master`, `test-PyPi` branches? `gh-pages` might still be problematic now, maybe we can give it 1 year until removing it? `release-v2.2` should also be safe to delete (the tag should still survive)

**Comment by lan496** [comment]
> can we delete: rc, master, test-PyPi branches?

> release-v2.2 should also be safe to delete (the tag should still survive)

Yes, I see no problem with deleting these branches.
But, I would like to leave the branch matters to @atztogo 

> gh-pages might still be problematic now, maybe we can give it 1 year until removing it? 

I do not see much benefit to deleting this branch since it just redirects to RtD.

**Comment by atztogo** [comment]
I agree with @LecrisUT and @lan496.
