### ISSUE TITLE
Mapping between settings of two Hall numbers

### ISSUE THREAD

**Issue by kbarros** [spglib/spglib#531]
Hi, thank you for the excellent library.

Does Spglib have a facility to find the affine transformation between two Hall numbers belonging to the same spacegroup number? 

This data appears to be available from the Bilbao server. For example, go to the ["Wyckoff Positions"](https://www.cryst.ehu.es/cryst/get_wp.html) page, enter spacegroup 227, then press "ITA settings" button. It shows two origin choices (2 and 1) for spacegroup Fd-3m. They differ by a shift of origin `[-1/8, -1/8, -1/8]`, as indicated by the P column in the image below:

<img width="550" alt="image" src="https://github.com/user-attachments/assets/cd674da5-78b3-4a89-b45a-751a81367faa">

Can I use Spglib to determine this affine transformation between the associated Hall numbers 525 (Fd-3m with origin 1) and 526 (Fd-3m with origin 2)?

As another example, on the ["Wyckoff Positions"](https://www.cryst.ehu.es/cryst/get_wp.html) page, for spacegroup 9, the "ITA settings" button shows 18 possible settings. These correspond to Hall numbers between 39 and 56 on [Seto's page](https://yseto.net/en/sg/sg1). I would like to obtain this column of transformations P.

<img width="438" alt="image" src="https://github.com/user-attachments/assets/29432c38-0352-4426-b31c-0e95129f2f75">

For example, is there a way to get the transformation `P = c, -b, a` that maps between Hall number 40 (`A 1 a 1`) and 39 (`C 1 c 1`)?

Perhaps Spglib could be used to build a function that takes one Hall number and returns (P, p) as a 3x3 matrix and a 3-vector translation, which transforms to the ITA "standard" Hall number?

**Comment by lan496** [comment]
Spglib does not suport to finding transformation between two arbitrary groups with the same space-group type so far.

That being said, [`get_spacegroup_type_from_symmetry`](https://spglib.readthedocs.io/en/stable/api/python-api/spglib/spglib.html#spglib.get_spacegroup_type_from_symmetry) can search a transformation between a given group and the spglib's representative for the space-group type, which is the first one in `hall_number` order.
So, calling `get_spacegroup_type_from_symmetry` for the space group with origin choice 2 may return one with origin choice 1 and the corresponding transformation in your example case.

**Comment by kbarros** [comment]
Thanks for your advice. I could not figure out how to extract the transformation matrix `P` between Hall numbers using Spglib functionality like `get_spacegroup_type_from_symmetry`.

However, for future reference, the full table of transformations `P` between Hall numbers is available here:
https://github.com/MaterSim/PyXtal/blob/1ba044cace1815d450e476a1fcb2fe8cb5798923/pyxtal/database/HM_Full.csv

Furthermore, PyXtal maps from spacegroup number to conventional Hall numbers (for both ITA and Spglib conventions), here:
https://github.com/MaterSim/PyXtal/blob/1ba044cace1815d450e476a1fcb2fe8cb5798923/doc/Settings.rst#space-group

These tables fully solve the problem for me. Perhaps these PyXtal tables could also be linked in the documentation for `get_symmetry_from_database`?

**Comment by lan496** [comment]
> Perhaps these PyXtal tables could also be linked in the documentation for get_symmetry_from_database?

I am not sure. This issue may be already a pointer to the information.
