### ISSUE TITLE
Versioning convention

### ISSUE THREAD

**Issue by merkys** [spglib/spglib#54]
I have noticed that the interface of spglib's C libraries sometimes changes between minor versions (for example, I had to rewrite some portions of code during the migration from spglib v1.8.2.2 to v1.10.3). I assume that [Semantic Versioning](https://semver.org/spec/v2.0.0.html) convention, requiring minor versions to be backwards compatible, is not used for spglib. My question is: is there a way to deduce from the version number which versions are compatible?

**Comment by atztogo** [comment]
The semantic versioning convention is too strict for me. I try not to change spglib API's often but it's difficult to predict which symmetry information is required by researchers, and those requirements are often beyond my imagination. In addition, sometimes I find theoretical problems in my definitions of APIs. These make me update APIs in some frequency, and I know people don't want spglib-v58.0.1.

The real problem is that I am too busy to be a good maintainer of spglib. So if you can help me, we may be able to follow the semantic versioning convention. For me, version number is just nothing more than showing the fact that the code is modified.

**Comment by merkys** [comment]
Not every change is a breaking one: if only new pieces of information are added to the C/Python data structures, everything else is left backwards compatible. Same holds with the clarifications/fixes of definitions, which could be branded as bugfixes/patches. On the other hand, v58 is nothing to be afraid of (Mozilla Firefox is at v59 already, and it still is second most popular desktop Web browser). In my opinion this is a price to pay to let the users know whether or not they have to migrate their own code upon updating the source they depend on.

Following the Semantic versioning should not be difficult to do. Python binding for spglib has some tests and they could be used to tell whether a recent change has introduced a breaking change (tests do not pass) or not (tests pass successfully without rewriting). Nevertheless, I understand the drawbacks of the Semantic versioning and it is the choice of the developer whichever convention to follow.

**Comment by atztogo** [comment]
OK. I will consult to you on the next update about how I should give the version number.

**Comment by jochym** [comment]
I second the gentle push towards systematic semantic versioning. OTOH I fully understand Togo's pain with versioning - I have the same problem with my packages. But at the end semantic versions deliver additional info to the users - so they are worth it.

**Comment by merkys** [comment]
I volunteer to review the next changelog entry and to suggest the type of change (breaking or non-breaking) – please ping me when you are about to release the new version. spglib is really a very useful piece of software, and GitHub is a pretty good choice for the community to gather.

**Comment by atztogo** [comment]
It is helpful. Thanks.

**Comment by atztogo** [comment]
I wrote a text on spglib and put on arxiv for the current version (v1.10.4), https://arxiv.org/abs/1808.01590 . Now I can refresh.

I am considering to release v2.0 or something like this in some near future. I will need @merkys 's help on the versioning. But the main point that I want to discuss is as follows. If we release v2.0, we can modify API. Do you have anything that you want to change API? How can I collect requests? There are other nice crystal symmetry software like cctbx that is now under a permissive free software license. Will spglib have any role? Crystallographic convention stuffs are probably better treated by gemmi,
http://gemmi.readthedocs.io/en/latest/sym.html.

**Comment by merkys** [comment]
Thanks for the link of a very interesting manuscript. It nicely presents
the math behind the spglib. Is it going to be published?

I will gladly review the API changes. Currently I have no feature requests,
but other users should be asked for comments using mailing list (and
possibly other channels).

While packaging spglib for Debian I became accustomed to more and more
software tools using spglib. The package is really popular and will
definitely be such due to its free license, well-written documentation,
variety of programming language bindings and robustness.

**Comment by atztogo** [comment]
Thanks @merkys . I've not yet considered if this spglib text will be submitted to some journal or not.

**Comment by mrakitin** [comment]
It's a very nice discussion about versioning. How about using https://github.com/warner/python-versioneer for binding the git tags to the Python package versions? Not sure how well it will work for the multi-language repo such as spglib, but it works quite well for pure Python projects. Worth to investigate.

It's an interesting approach to the project structure of the multi-language project here. We with @stuartcampbell at NSLS-II may use it as an example for one of our projects (Fortran+Python), and maybe for more later.

**Comment by atztogo** [comment]
@merkys, I think currently spgilb well respects the semantic versioning. So I would like to close this issue. But please reopen whenever you feel it is needed.

**Comment by merkys** [comment]
@atztogo you are right, this is an old issue that should have been closed before.
