### ISSUE TITLE
Wish list toward v2.0

### ISSUE THREAD

**Issue by atztogo** [spglib/spglib#65]
- [x] Make k-point grid ID variables from ``int`` (``intc`` in numpy) to ~~``long``~~ ``size_t`` (``uintp`` in numpy) to support very dense mesh. Considering memory demanding, preparing both or a macro switch may be better.
- [x] Site symmetry corresponding to Wyckoff letter
- ~[ ]~ Remove ``mapping_to_primitive`` and ``primitive_lattice`` in the spglib dataset to avoid confusion. This will be done when v2.0 release because it breaks the backward compatibility. (Let's keep this.)
- [x] Abandon configure script (autotools) support
- [x] Treatment of non-collinear magnetic moment with rotation matrix det|R| R
- [x] Rename `get_hall_number_from_symmetry` (issue #132) -> `spg_get_symmetry_from_database` (`get_hall_number_from_symmetry` will be deprecated at v2.0)
- [x] Magnetic space group type search

**Comment by atztogo** [comment]
Transformation matrix from the standardized basis to the primitive basis is listed here, https://atztogo.github.io/spglib/definition.html#transformation-to-the-primitive-cell. So multiply these two transformation matrices gives what you want. Do you want me to write a short document on this?

**Comment by MPiotr** [comment]
Thank you, I've missed that part. I think adding a link to this paragraph somewhere in the python interface documentation would be useful.

**Comment by atztogo** [comment]
Thanks for your suggestion. I added one sentence of it.
https://atztogo.github.io/spglib/api.html#origin-shift-and-lattice-transformation . I wrote it at C-API secition but it is clearly linked from transformation matrix part of python interface documentation.

**Comment by toxa81** [comment]
Generation of k-points for non-collinear spin configuration with and without spin-orbit coupling.

**Comment by atztogo** [comment]
@toxa81 That's a good idea. I can write it by my guess of the definition, but I must want to know the clear definition. Do you know about it e.g. by paper etc?

**Comment by toxa81** [comment]
@atztogo There is not much of good reading available regarding the symmetry operations on spinor wave-functions. The best explanation we found so far was in this presentation https://courses.cit.cornell.edu/ece407/Lectures/handout_symmetries.pdf
(pages 8 - 10). Basically, in case of spin-orbit coupling you need to “rotate” spinor wave-functions using the same symmetry operation for both r-coordinates and spin components. This impacts the symmetries in reciprocal space and k-point generation. 
The most readable implementation of magnetic symmetry detection for crystals is implemented in the Elk electronic structure code (http://elk.sourceforge.net/), in the findsym.f90. They loop over symmetries of the crystal and apply them to atomic positions and spin moment (3d Cartesian vector) and check if it transforms to en equivalent atom with a “rotated” spin moment. But(!) in case of spin-orbit coupling they restrict the spin symmetry to the current spacial symmetry. Once the magnetic symmetries are found, their rotational part is used to reduce the k-points of the full Brillouin zone.

**Comment by atztogo** [comment]
Thanks for these information. I will read the texts. I will not read the code of elk to avoid problems.

**Comment by toxa81** [comment]
@atztogo Elk is GNU open source code, there should not be any problems with it. We do more or less the same in our BSD code, but we don't have spin-orbit support yet: https://github.com/electronic-structure/SIRIUS/blob/develop/src/Unit_cell/unit_cell_symmetry.hpp

**Comment by atztogo** [comment]
The pdf is very good. I haven't had experience of calculations with spin-orbit coupling. In usual applications, if I understand correctly, the space group operations are searched from the direct product space of atomic positions and magnetic moment vectors on the atoms. The point group is the the collection of the rotation parts. Then the irreducible k-points are searched in the same way as non-magnetic case. But I don't have idea how I should treat the time reversal symmetry. Maybe good for spglib just to provide space group operations, and users will compute irreducible k-points using `spg_get_stabilized_reciprocal_mesh` (https://atztogo.github.io/spglib/api.html#spg-get-stabilized-reciprocal-mesh) with `num_q=1` and `qpoints = {0, 0, 0}` by themselves.

**Comment by toxa81** [comment]
>But I don't have idea how I should treat the time reversal symmetry.
I think in one case you use a direct product of space and magnetic operations, in the second case you just use the space operations to rotate both atoms and magnetic moments. 

`spg_get_stabilized_reciprocal_mesh()`
that's a good hint! I can definitely use that function.

**Comment by atztogo** [comment]
@toxa81 I have implemented an on-site vector treatment targeting a non-collinear case. With `tensor_rank==1` and `is_magnetic==1`, magnetic moments are rotated by the rotation matrix of det|R| R. https://github.com/atztogo/spglib/blob/develop/src/spin.c

Combined with `spg_get_stabilized_reciprocal_mesh()`, I think k-points are generated under this non-collinear condition. This feature will be documented at v2.0.

I finally have no idea how to treat spin-orbit coupling from spglib.

**Comment by goodluck1982** [comment]
I also expect spglib v2.0 can support the 1651 magnetic space groups (MSG, i.e. Shubnikov space group). I expect spglib v2.0 can determine the MSG symmetries and indentify its MSG name according to given atomic positions and atomic magnetic moments in a unit cell. 

As for the spin-orbit coupling (SOC), I don't think spglib needs to consider it directly. Because SOC involves "double space group (DSG)" and the elements of DSG are nothing but the elements of the corresponding SG plus  those obtained by multiplying them by \bar{E}. Accordingly, if the SG of a system has been determined by spglib, say SG 187, then the DSG of the system is  directly DSG 187.  As long as SG is determined, the corresponding DSG is also determined. SOC or DSG cannot be embodied by the atomic species and positions in a cell. 

In addition, it's known that one SO(3) rotation R corresponds to two SU(2) spin rotation g and -g. This will result in nondeterminacy to name the spin rotation matrix in a double group. For example,  if g={{0,i},{i,0}}, then both g and -g correspond to the SO(3) rotation C2x, but in double group which SU(2) matrix, g or -g, is named C2x can be dertermined by users arbitrarily in principle. That is to say, it's right that g is C2x and -g is \bar{C2x}, while it's also all right that g is \bar{C2x} and -g is C2x.

**Comment by atztogo** [comment]
@goodluck1982, thanks for your information about SOC.
To assign the magnetic space group type, spglib has to have the MSG database. Currently I can't find those database whose license is clear. If this issue is solved, the implementation will be possible, though I may not have enough time to work on it for a while. But this will be implemented as the post-processing after the space group type search in spglib. This means that the MSG type assignment is approximately independent, so it is also considered nice to be done out of spglib.

**Comment by goodluck1982** [comment]
> To assign the magnetic space group type, spglib has to have the MSG database. Currently I can't find those database whose license is clear.

You can refer to https://iso.byu.edu/iso/magneticspacegroups.php

**Comment by goodluck1982** [comment]
> Thanks @goodluck1982. This information is for the citation but not the software (or data) license.

Yes, the web page does not say clearly its license. 

I notice that the help file `isoman.pdf` in the `iso.zip` package says the following words. 
![image](https://user-images.githubusercontent.com/48718961/154632731-4c0511c8-91f9-496c-bfdf-2f9b6e76f64f.png)

And, at the begining of of the file https://iso.byu.edu/iso/magnetic_table_bns.txt there are the following descriptions.
```
Magnetic Space Groups
Compiled by Harold T. Stokes and Branton J. Campbell
Brigham Young University, Provo, Utah, USA
June 2010

Table 1.  Listed in order of BNS number

BNS: Setting of N. V. Belov, N. N. Neronova and T. S. Smirnova
OG:  Setting of W. Opechowski and R. Guccione

This data is based on data from:
Daniel Litvin,"Magnetic Space Group Types," Acta Crystallographica (2001)
  A57 729-730. (http://www.bk.psu.edu/faculty/litvin/Download.html)
C. J. Bradley and A. P. Cracknell, The Mathematical Theory of Symmetry in
  Solids" (Clarendon Press, Oxford, 1972).
----------
Definition of point operator symbols (from Litvin)
Non-hexagonal groups:
1        x,y,z
4x       x,-z,y
4x-1     x,z,-y
4y       z,y,-x
4y-1     -z,y,x
.
.
.
```

Maybe it's better to consult the authors of ISOTROPY directly for the usage of the data.

**Comment by atztogo** [comment]
Thanks. If the data license is clear like an open data license, it is fine. But the license that you show is still unclear. For the easy use from spglib, the data is expected to be written in the spglib source code. This way of using is probably unexpected for them,  and as you wrote,  we must ask to them anyway (of course even if it is an open license.)

**Comment by goodluck1982** [comment]
An alternative method is to collect data directly from the books

[1] Daniel B. Litvin,  Magnetic Group Tables
ISBN 978-0-9553602-2-0    [doi:10.1107/978095536022000](http://dx.doi.org/10.1107/9780955360220001)

[2] C. J. Bradley and A. P. Cracknell, The Mathematical Theory of Symmetry in   Solids" (Clarendon Press, Oxford, 1972).

**Comment by atztogo** [comment]
@goodluck1982, the extended Hall symbols in the following paper can be implemented if I have time,
https://onlinelibrary.wiley.com/doi/abs/10.1107/S1600576720015897

**Comment by atztogo** [comment]
I would like to close this issue because v2.0 was released. The wish list toward v3.0 is found at #185.
