### ISSUE TITLE
install path of the headers

### ISSUE THREAD

**Issue by toxa81** [spglib/spglib#75]
`autotools` install the headers into $PREFIX/include/spglib/* while `cmake` installs a single spglib.h header into $PREFIX/include/spglib.h

What is the expected install path and what is a deprecated path?

**Comment by atztogo** [comment]
I have no specific install path. I expect users decide it.

**Comment by toxa81** [comment]
Well, of course. But `autotools` will place the headers under the **spglib** subfolder inside the **include** directory but not the `cmake`. This means the the host code has to choose between
```
#include <spglib/spglib.h>
```
and
```
#include <spglib.h>
```

**Comment by atztogo** [comment]
I see. I finally failed to use autotools well. Cmake is now enough poplular. Do you think I am allowed to remove autotools support?

**Comment by toxa81** [comment]
>Do you think I am allowed to remove autotools support?
Yes, I think so. CMake works just fine and there is no need to replicate the build process with `autotools`.

**Comment by StefanBruens** [comment]
avogadrolibs expects it to be installed as spglib/spglib.h, so is may be better to use the autoconf location.

**Comment by atztogo** [comment]
@StefanBruens, could you tell more in detail?

**Comment by StefanBruens** [comment]
https://github.com/OpenChemistry/avogadrolibs/blob/master/cmake/FindSpglib.cmake

Also the sources contain "#include <spglib/spglib.h>

So preferably, DESTINATION should be "%{CMAKE_INSTALL_INCLUDEDIR}/spglib"

**Comment by atztogo** [comment]
How about 
```
install(TARGETS symspg LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR})
```
?

**Comment by LecrisUT** [comment]
Maybe this can be considered as part of the `2.0` release. Overall the standard syntax is that the main interface header is in the top include. Others use foldered structure if they want to include only components of the library. This is unnecessary for this library.

As for downstream users, it would be great if someone can contact the devs to switch to using simple `find_package` or `FetchContent` now that these will be available in the next minor release

**Comment by lan496** [comment]
@LecrisUT This issue seems to be resolved. Can I close this issue?

**Comment by LecrisUT** [comment]
Good with me. Spglib's api is a single-header library so it shouldn't have a dedicated folder
