### ISSUE TITLE
A bug?  std_lattice is not a Rhombohedral  lattice.

### ISSUE THREAD

**Issue by goodluck1982** [spglib/spglib#87]
I use spglib to analyze group symmetries. When I treate a space group with rhombohedral lattice, say R3 space group (No.146), the  obtained lattice, i.e. the std_lattice from get_symmetry_dataset, which is the same with  refine_cell, is a hexagonal cell, not a primitive rhobobohedral  cell as described in [https://atztogo.github.io/spglib/definition.html#def-idealize-cell](url).

Although find_primitive can give a rhombohedral cell, yet its orientation is not the one described in the above web page,  which says that a_xy is along +x direction.

The test structure is in the vasp format,

>New structure
1.0
        3.0000000000         0.0000000000         0.0000000000
       -0.5209445330         2.9544232590         0.0000000000
       -0.5209445330        -0.6208375187         2.8884559143
    C    
    3   
Direct
     0.100000001         0.200000003         0.699999988
     0.699999988         0.100000001         0.200000003
     0.200000003         0.699999988         0.100000001

The generated std_lattice by get_symmetry_dataset or  refine_cell is a hexagonal lattice as follow
>[[ 4.59626666        0.            0.        ]
 [-2.29813333    3.98048369    0.        ]
 [ 0.          0.           4.19797551]]

The cell given by find_primitive is as follow (a rhombohedral cell with a_xy not in +x direction)
>[[ 2.29813333  1.3268279   1.39932517]
 [-2.29813333  1.3268279   1.39932517]
 [ 0.         -2.65365579  1.39932517]]

The behavior of neither get_symmetry_dataset  nor find_primitive agrees with the description in [https://atztogo.github.io/spglib/definition.html#def-idealize-cell](url). Is this a bug?

**Comment by atztogo** [comment]
Have you read https://atztogo.github.io/spglib/api.html#spg-find-primitive?

**Comment by goodluck1982** [comment]
> Have you read https://atztogo.github.io/spglib/api.html#spg-find-primitive?

Yes I have read it. I tried `standardize_cell(input_cell, to_primitive=True)`,  and it gived the same result with find_primitive. What I mean is that the behavior is not as described in the web page [https://atztogo.github.io/spglib/definition.html#def-idealize-cell.](url) .  According to my understanding, the web page  provides the idealized configuration for each lattice.  On the  side, the description about std_lattice of get_symmetry_dataset is "Standardized crystal structure **after idealization**". That is to say std_lattice should have the idealized configuration in [https://atztogo.github.io/spglib/definition.html#def-idealize-cell.](url) .  But the fact is not this.

**Comment by goodluck1982** [comment]
I use the latest version 1.14.1

**Comment by atztogo** [comment]
The default behaviour is to return with the hexagonal setting, then `to_primitive=True` applies this transformation P_R for that of hexagonal given at https://atztogo.github.io/spglib/definition.html#transformation-to-the-primitive-cell .

What you expect is probably, let's take space group No.146, the setting R given at 
http://pmsl.planet.sci.kobe-u.ac.jp/~seto/?page_id=37&lang=en
The default behaviour is to give the setting H.

**Comment by goodluck1982** [comment]
Now I know that the default behavior is to give the H setting. If I use `hall_number=434` (434 for R setting of R3 space group) in `get_symmetry_dataset`, then the obtained std_lattice is as follow:
>    2.2981333293,    -1.3268278963,     1.3993251709
    0,                           2.6536557927,     1.3993251709
   -2.2981333293,    -1.3268278963,     1.3993251709

This is a rhombohedral  lattice now, but its a_xy is still not in +x direction.
According to the transformation P_R given in [https://atztogo.github.io/spglib/definition.html#transformation-to-the-primitive-cell](url),
the obtained rhombohedral basic vectors a1,a2,a3 from the idealized hexagonal basic vectors a,b,c is shown is the fig.(a) below.  However, the page [https://atztogo.github.io/spglib/definition.html#def-idealize-cell](url) says the idealized rhombohedral basic vectors should be the fig.(b) below.

![hex-rhom](https://user-images.githubusercontent.com/48718961/74643513-ce455b80-51af-11ea-9df8-455b45f7728f.PNG)

Therefore, if the behaviors of both get_symmetry_dataset and find_primitive do not have problem, then the description in [https://atztogo.github.io/spglib/definition.html#def-idealize-cell](url) should be changed to be consistent with the program's behavior.

**Comment by atztogo** [comment]
Oh, I am sorry. I was wrong!
Then how I should do... If anyway the documentation has to be fixed, it's a good change to change the behaviour, too, to make it intuitive. I guess not many people have used specifying hall symbol with R setting. So maybe it's good to give the same for both cases and update documentation following this. How do you think?

**Comment by atztogo** [comment]
And thank you very much for your pointing this!

**Comment by goodluck1982** [comment]
You are welcome. I also thank you for writing and sharing spglib, a very useful tool, and timely reply to my question. In my opinion,  to keep the consistence between document and program's behavior and to keep the behavior intuitive are both important.  An alternative option may be:
(1). Keep the behavior of refine_cell and std_lattice, and update the document to point out explicitly that H setting is used for R lattice by default.
(2). For R lattice, either change the behavior of find_primitive to fit the document's orientation, or change the document to fit the behavior of find_primitive. But the former cannot be described only by the P_R matrix in [https://atztogo.github.io/spglib/definition.html#transformation-to-the-primitive-cell](url), in which case another rotation should be followed. In a another word, the idealized standard lattice settings for H and R in the present document can not be related only by transformation essentially and another rotation is needed.

**Comment by atztogo** [comment]
Thanks for your advise.
(1) will be done.

(2) Let's take the later. I summarize this as follows:

### How it works currently.
We keep the behaviour of H setting and the transformation matrix P_R. Then we get the basis vectors for the primitive cell such as in your example:
```
[[ 2.29813333 1.3268279 1.39932517]
[-2.29813333 1.3268279 1.39932517]
[ 0. -2.65365579 1.39932517]]
```
We will take this set of the basis vectors to be returned by the R setting.  But currently it works as you pointed out:
```
[[2.2981333293, -1.3268278963, 1.3993251709]
[0, 2.6536557927, 1.3993251709]
[-2.2981333293, -1.3268278963, 1.3993251709]]
```
I had completely forgotten about how I implemented, but the code was indeed implemented to be so here, 
https://github.com/atztogo/spglib/blob/f8ddf5b2b242c6f1b8cf090545e236a48dffe06b/src/refinement.c#L807-L829

### What we have to do
(a) We will fix the code above ``set_rhomb`` to fit with the result from the combination of H setting and P_R.
(b) Documentation of https://atztogo.github.io/spglib/definition.html#rhombohedral-lattice will be fixed to fit (a).

**Comment by atztogo** [comment]
I'm sorry that I'm late to fix this.

I fixed the issues along my previous comment above and it's now in develop branch. I shortly mention about the choice of settings in the documentation, and updated rhombohedral lattice section of https://atztogo.github.io/spglib/definition.html#def-idealize-cell,

**Comment by goodluck1982** [comment]
I compare the dataset generated by versions 1.14.1 and 1.15.0 and find that nothing is changed except  new items crystallographic_orbits and primitive_lattice for version 1.15.0.  In fact,  I think the codes do not need change and only the documents need change to be consistent with the codes. Because the present standardized lattice after idealization  are the same with ITA [International Tables for Crystallography Vol. A, 5th ed (2005)] .

**Comment by atztogo** [comment]
The code is not yet released and is current on the develop branch. What I have made is to be consistent for the R setting by `find_primitive` and `get_symmetry_dataset` with specific `hall_number` of R setting. As you pointed out, they are different. Now they are same. I changed the later behaviour. Maybe what I wanted to do can be read from this test script, https://github.com/atztogo/spglib/blob/develop/python/test/test_rhomb_H_and_R.py.

The change is this:
https://github.com/atztogo/spglib/blob/d14e2b9a4f11aa301683d1e1abbb75f1c33a9ea7/src/refinement.c#L858-L866

This part was:
https://github.com/atztogo/spglib/blob/5fd17a8e89be69f8da490e84ff48d988a7f7f7f0/src/refinement.c#L858-L865

**Comment by goodluck1982** [comment]
I see. I didn't check the data with `specific hall_number` . I just used the default (first) Hall setting for each space group number.
Yes, the behavior of  `get_symmetry_dataset ` with `specific hall_number` should be fixed to be consistent with  `find_primitive `  for R settings.

**Comment by atztogo** [comment]
I close this issue because it is fixed (hopefully).
