### ISSUE TITLE
libm inclusion breaks msvc build

### ISSUE THREAD

**Issue by bodomartin** [spglib/spglib#94]
Hi could you put around the lines in the main CMakeLists.txt

target_link_libraries(symspg m)
target_link_libraries(spglibtest m)

if( NOT MSVC) 

endif()

please? the latest changes break the MSVC build

The change is trivial but I can create a pull request if wanted

**Comment by atztogo** [comment]
Thanks. I would like you to send PR. I will merge.

**Comment by bodomartin** [comment]
all but the check target (test.c) compiles, but the code in test.c uses variable-sized arrays
in function 'test_spg_get_ir_reciprocal_mesh' (gcc extension)

I guess the code should stay in C , so should I use new/free or submit the patch without? .. I would then deactivate building the check target for msvc.

**Comment by atztogo** [comment]
I have never tried to use msvc. So I don't know the detail. But if I remember correctly, msvc doesn't support c99? I removed variable-sized arrays in `test.c` (05ee8f51 and 3ab8005c). But I can't do the test by msvc. Could you have a look at it?

**Comment by bodomartin** [comment]
I have tried to fix the CMakeLists.txt for MSVC,
but I cannot run make check (also for the gcc build, heap corruption problem)

**Comment by atztogo** [comment]
Thanks for letting me know it. I will have a look at it more in detail.

**Comment by bodomartin** [comment]
sorry, my fault not merging to develop. done now - I use git always but not much with github (yet)

**Comment by atztogo** [comment]
I found memory leak. The fix is this, 2e050b38. Thanks for your pointing.
I got a bug report that is critical. So I have to release v1.15.1 very soon. I may not wait for your response on this heap corruption problem before the release.

**Comment by bodomartin** [comment]
please go ahead with the release

**Comment by bodomartin** [comment]
I was too quick for the msvc check, which still fails. I will have a look the next few days and submit a pull request. Anyway, the library now builds with msvc which is good.

**Comment by atztogo** [comment]
OK. Thanks!

**Comment by atztogo** [comment]
Can I close this issue?

**Comment by bodomartin** [comment]
yes
