### ISSUE TITLE
Create an organization for spglib

### ISSUE THREAD

**Issue by seatonullberg** [spglib/spglib#99]
I would like to suggest creating a GitHub organization for this project. In my experience, creating separate repositories for language bindings or other associated tools can often make it easier to adhere to the idiomatic styling guidelines of each without sacrificing their shared namespace. 

If this were to be implemented I could make the following improvements to the Rust bindings:

* Automatically host documentation for the latest version on the [docs.rs](https://docs.rs/) site

* Provide the compile-time ability to build the latest version of `spglib` from source if the package is not already installed by the user

Hopefully this issue can serve as a discussion board to weigh the pros and cons.

**Comment by atztogo** [comment]
Thanks for your suggestion. Definitely I agree and it was planned. I am just lazy. I made it for phonopy (https://phonopy.github.io/phonopy/). I will work on this for spglib in a few days.

**Comment by atztogo** [comment]
This is done. So I will close this issue.
